/**
 * GAIA Shared TypeScript Library
 *
 * Shared utilities for GAIA TypeScript/JavaScript applications.
 */

// `./analytics` is intentionally NOT re-exported here. It pulls in
// `posthog-node` which imports Node-only modules (`path`, `fs`) that
// Metro/React Native cannot resolve. Bot consumers should import it
// via the subpath: `import { Analytics } from "@gaia/shared/analytics"`.
export {
  type AddPublicIntegrationParams,
  type AddToWorkspaceParams,
  type ApiClientConfig,
  ApiError,
  type BatchSyncConversationsParams,
  type BulkNotificationAction,
  type BulkNotificationActionParams,
  buildIntegrationUrl,
  buildQueryString,
  buildSearchQuery,
  buildUrl,
  type ChatStreamFileData,
  type ChatStreamMessage,
  type ChatStreamParams,
  type ChatStreamReplyTo,
  CONVERSATION_ENDPOINTS,
  type CommunityIntegrationsParams,
  type ConnectIntegrationParams,
  type ConnectParams,
  type ConversationListParams,
  type ConversationSyncItem,
  type CreateCustomIntegrationParams,
  createApiHeaders,
  type DisconnectParams,
  type GenerateImageParams,
  INTEGRATION_ENDPOINTS,
  type IntegrationAddPublicResponse,
  type IntegrationConnectResponse,
  type IntegrationListParams,
  type IntegrationPublishResponse,
  type IntegrationStatusEntry,
  type IntegrationStatusResponse,
  type IntegrationUnpublishResponse,
  type IntegrationWorkspaceAddResponse,
  type McpTestConnectionResponse,
  NOTIFICATION_ENDPOINTS,
  type NotificationListParams,
  type NotificationReadStatusParams,
  type NotificationStatusFilter,
  normalizeListResponse,
  type PinMessageParams,
  type RenameConversationParams,
  type SearchApi,
  SearchApiEndpoints,
  type SearchIntegrationsParams,
  type SearchMode,
  type SnoozeNotificationParams,
  type StarConversationParams,
  type SubtaskCreateParams,
  type SubtaskUpdateParams,
  type TestConnectionParams,
  type TestNotificationParams,
  TODO_ENDPOINTS,
  type TodoBulkActionParams,
  type TodoBulkMoveParams,
  type TodoListParams,
  type TodoSemanticSearchParams,
  type UpdateChannelPreferenceParams,
  WORKFLOW_ENDPOINTS,
  type WorkflowCommunityParams,
  type WorkflowCreateParams,
  type WorkflowExecutionsParams,
  type WorkflowFromTodoParams,
  type WorkflowGeneratePromptParams,
  type WorkflowListParams,
  type WorkflowRegenerateParams,
  type WorkflowTriggerOptionsParams,
  type WorkflowUpdateParams,
} from "./api";
export {
  type AuthenticatedSettingsResponse,
  type AuthStatus,
  allCommands,
  authCommand,
  BaseBotAdapter,
  BOT_MEDIA_LIMITS,
  type BotCommand,
  type BotCommandOption,
  type BotConfig,
  type BotConversation,
  type BotConversationListResponse,
  type BotCreateTodoRequest,
  type BotFileData,
  type BotLogFields,
  type BotLogger,
  BotServer,
  type BotSubcommand,
  type BotTodo,
  type BotTodoListResponse,
  type BotUserContext,
  type BotWorkflow,
  type BotWorkflowExecutionRequest,
  type BotWorkflowExecutionResponse,
  type BotWorkflowListResponse,
  buildAuthLinkMessage,
  type ChatRequest,
  COMMAND_HELP,
  type CommandContext,
  type CommandExecuteParams,
  chunkResponse,
  conversationsCommand,
  convertToDiscordMarkdown,
  convertToSlackMrkdwn,
  convertToTelegramHtml,
  convertToWhatsAppMarkdown,
  createBotLogger,
  dispatchTodoSubcommand,
  dispatchWorkflowSubcommand,
  escapeHtml,
  escapeHtmlAttr,
  extensionForMime,
  extractSubcommandArgs,
  formatBotError,
  formatConversation,
  formatConversationList,
  formatTodo,
  formatTodoList,
  formatWorkflow,
  formatWorkflowList,
  friendlyMediaError,
  GaiaApiError,
  GaiaClient,
  gaiaCommand,
  getHttpStatus,
  handleConversationList,
  handleNewConversation,
  handleStreamingChat,
  handleTodoComplete,
  handleTodoCreate,
  handleTodoDelete,
  handleTodoList,
  handleWorkflowCreate,
  handleWorkflowDelete,
  handleWorkflowExecute,
  handleWorkflowGet,
  handleWorkflowList,
  hashLogIdentifier,
  helpCommand,
  htmlToPlainText,
  type IncomingMedia,
  type IntegrationInfo,
  injectInfisicalSecrets,
  isTableRow,
  isTableSeparator,
  loadConfig,
  type MediaKind,
  type MediaOutcome,
  type MessageEditor,
  type MessageTarget,
  mediaKindFromMime,
  type NewMessageSender,
  newCommand,
  OUTBOUND_FILE_LIMITS,
  type OutboundAttachment,
  type OutboundMessageEnvelope,
  outboundAttachmentSchema,
  outboundMessageEnvelopeSchema,
  PLATFORM_LIMITS,
  PLATFORM_MARKDOWN,
  type PlatformName,
  parseTextArgs,
  processBotMedia,
  type RichMessage,
  type RichMessageTarget,
  renderForPlatform,
  richMessageToMarkdown,
  type SentMessage,
  type SettingsResponse,
  STREAMING_DEFAULTS,
  type StreamingOptions,
  sanitizeErrorForLog,
  settingsCommand,
  statusCommand,
  stopCommand,
  todoCommand,
  truncateResponse,
  type UnauthenticatedSettingsResponse,
  unlinkCommand,
  unsupportedMediaMessage,
  workflowCommand,
} from "./bots";
export {
  type ApiFileData,
  type ApiToolData,
  type ArtifactData,
  applyStreamEvent,
  type CalendarDeleteOptions,
  type CalendarEditOptions,
  type CalendarEventDateTime,
  type CalendarFetchData,
  type CalendarListFetchData,
  type CalendarOptions,
  type ChatStreamEvent,
  type CodeChartData,
  type CodeData,
  type CodeOutput,
  type ContactData,
  type Conversation,
  createTurnAccumulator,
  type DeepResearchResults,
  type DeepResearchSource,
  type EmailComposeData,
  type EmailFetchData,
  type EmailSentData,
  type EmailThreadData,
  type EmailThreadMessage,
  type EnhancedWebResult,
  extractToolProgressMessage,
  type GenericToolData,
  type GoogleDocsData,
  type GoogleDocsDocument,
  type GroupedConversations,
  getFixture,
  getToolData,
  type ImageResult,
  isKnownTool,
  type MCPAppData,
  mergeToolOutputIntoToolData,
  type NewsResult,
  type PeopleSearchData,
  parseChatStreamEvent,
  type RateLimitData,
  REASONING_TOOL_NAME,
  type RecurrenceData,
  type RecurrenceRule,
  type RedditCommentCreatedData,
  type RedditCommentData,
  type RedditData,
  type RedditPostCreatedData,
  type RedditPostData,
  type RedditSearchData,
  type ReplyToMessageData,
  type SameDayEvent,
  type SearchResults,
  type SharedMemoryData,
  type StreamToolDataEntry,
  type StreamToolOutput,
  SUBAGENT_GROUP_TOOL_NAME,
  type SubagentEndPayload,
  type SubagentGroupData,
  type SubagentStartPayload,
  TOOL_CALLS_DATA_TOOL_NAME,
  TOOL_FIXTURES,
  type TodoAction,
  type TodoItem,
  type TodoPriority,
  type TodoProgressData,
  type TodoProgressItem,
  type TodoProgressSnapshot,
  type TodoProgressStatus,
  type TodoProject,
  type TodoSubtask,
  type TodoToolData,
  type TodoToolStats,
  type ToolCallEntry,
  type ToolDataEntry,
  type ToolDataMap,
  type ToolFixture,
  type ToolName,
  type TurnAccumulator,
  type TwitterData,
  type TwitterFollowersData,
  type TwitterPostCreatedData,
  type TwitterPostPreviewData,
  type TwitterSearchData,
  type TwitterTimelineData,
  type TwitterTweetData,
  type TwitterUserData,
  updateSubagentInToolData,
  upsertTodoProgressToolData,
  type WeatherData,
  type WebResult,
  type WorkflowCreatedData,
  type WorkflowDraftData,
} from "./chat";
export {
  CLI_COMMAND_DESCRIPTIONS,
  REQUIRED_DOC_COMMANDS,
  REQUIRED_INSTALL_COMMANDS,
} from "./cli";
export {
  USAGE_DANGER_THRESHOLD,
  USAGE_WARN_THRESHOLD,
} from "./constants/usage";
export {
  DESKTOP_TOOL_DEFAULT_TIMEOUT_MS,
  DESKTOP_TOOL_NAMES,
  type DesktopAppIconOption,
  type DesktopMediaAccessStatus,
  type DesktopPermissionPane,
  type DesktopPermissionStatus,
  type DesktopScreenshotData,
  type DesktopSettings,
  type DesktopSettingsSnapshot,
  type DesktopShortcutUpdateResult,
  type DesktopToolName,
  type DesktopToolRequest,
  type DesktopToolResult,
  type DesktopWindowInfo,
  isDesktopToolName,
} from "./desktop-tools";
export {
  categorizeIntegrations,
  filterIntegrations,
  filterNotifications,
  filterTodos,
  filterWorkflows,
  getIntegrationDisplayStatus,
  getNotificationIcon,
  groupNotificationsByDate,
  groupTodosByDate,
  groupTodosByProject,
  IntegrationQueryKeys,
  type IntegrationStatusDisplay,
  type NotificationFilter,
  NotificationQueryKeys,
  sortTodos,
  sortWorkflows,
  type TodoFilterState,
  TodoQueryKeys,
  type WorkflowFilterState,
  WorkflowQueryKeys,
} from "./hooks";
export {
  buildWorkflowStatusEntry,
  type CreateTodoStoreOptions,
  createTodoApi,
  createTodoStore,
  type HttpAdapter,
  isWorkflowStatusFresh,
  type NotifyAdapter,
  type RequestOptions,
  type SemanticSearchOptions,
  type TodoApiClient,
  type TodoStore,
  type TodoStoreHook,
  WORKFLOW_STATUS_TTL_MS,
  WORKFLOW_WS_EVENTS,
  type WorkflowGenerateResult,
  type WorkflowStatusCacheEntry,
  type WorkflowStatusResult,
} from "./todos";
export { formatToolDueDate, groupEventsByDate } from "./tool-utils";
export {
  type ActivityDay,
  type BudgetWindow,
  type BulkMoveRequest,
  type ChannelPlatform,
  type ChannelPreferences,
  type CommunityIntegration,
  type CommunityIntegrationsResponse,
  type CommunitySearchParams,
  type CommunityWorkflow,
  type ContentCreator,
  type CreateCustomIntegrationRequest,
  type CreateWorkflowPayload,
  type CronValidationResult,
  DEFAULT_MODELS,
  type DiscoverSkillsResponse,
  type ExecutionConfig,
  type FeatureUsage,
  type FileData,
  FileType,
  type FileUploadResult,
  getFileType,
  getModelById,
  getModelsByProvider,
  type ImageData,
  type InAppNotification,
  type InAppNotificationContent,
  type Integration,
  type IntegrationAuthType,
  type IntegrationCategory,
  type IntegrationCreator,
  type IntegrationManagedBy,
  type IntegrationStatusRecord,
  type IntegrationStatusValue,
  type IntegrationTool,
  type IntegrationToolsResponse,
  type LLMModel,
  type MarketplaceIntegration,
  type Memory,
  type MemoryCreate,
  type MemorySearchParams,
  type MemorySearchResponse,
  MODEL_ENDPOINTS,
  ModelProvider,
  type MyIntegrationItem,
  type MyIntegrationsResponse,
  type Note,
  type NoteCreate,
  type NoteListResponse,
  type NoteUpdate,
  type NotificationAction,
  type NotificationActionConfig,
  NotificationActionStyle,
  NotificationActionType,
  NotificationStatus,
  type PaginationMeta,
  type PlatformLink,
  type PlatformLinksResponse,
  Priority,
  type Project,
  type ProjectCreate,
  type ProjectUpdate,
  type PublicIntegrationResponse,
  type QuietHours,
  type Reminder,
  type ReminderCreate,
  type ReminderStatus,
  type ReminderUpdate,
  type SearchConversationResult,
  type SearchMessageResult,
  type SearchNoteResult,
  type SearchParams,
  type SearchResponse,
  type SearchResult,
  type Skill,
  type SkillCreate,
  type SkillStatus,
  type SkillTool,
  type SubTask,
  type Todo,
  type TodoCounts,
  type TodoCreate,
  type TodoFilters,
  type TodoLabel,
  type TodoListResponse,
  type TodoUpdate,
  type Tool,
  type ToolCategory,
  type ToolsByCategoryResponse,
  type ToolsListResponse,
  type TriggerConfig,
  type UsageActivity,
  type UsageBudget,
  type UsagePeriod,
  type UsageSummary,
  type UserIntegration,
  type Workflow,
  type WorkflowListResponse,
  type WorkflowMetadata,
  type WorkflowResponse,
  WorkflowStatus,
  type WorkflowStep,
} from "./types";
export {
  type ContentSegment,
  DEFAULT_SIMILARITY_CONFIG,
  type DueChipTone,
  dispatchOpenUIAction,
  extractUrls,
  formatCompactNumber,
  formatCurrency,
  formatDate,
  formatDateUTC,
  formatDueDate,
  formatDuration,
  formatFeatureName,
  formatFileSize,
  formatNumber,
  formatPlanName,
  formatRelativeDate,
  formatRelativeTime,
  formatRunCount,
  getCompleteTimeBasedGreeting,
  getDueChipTone,
  getRandomThinkingMessage,
  getRelevantLoadingMessage,
  getRelevantThinkingMessage,
  getSimpleTimeGreeting,
  getTriggerLabel,
  isOverdue,
  isTokenExpired,
  type JwtPayload,
  NEW_MESSAGE_BREAK_TOKEN,
  NEW_MESSAGE_BREAK_TOKEN_LENGTH,
  normalizeOpenUICode,
  OPENUI_SAMPLES,
  type OpenUIActionEventLike,
  type OpenUIActionHandlers,
  type OpenUILibraryLike,
  type OpenUISample,
  type ParsedContent,
  PLAYFUL_THINKING_MESSAGES,
  parseCronToHuman,
  parseJwt,
  parseOpenUISegments,
  parseQuickAdd,
  parseRelativeDateLabel,
  parseThinkingFromText,
  type QuickAddOptions,
  type QuickAddProject,
  type QuickAddProjectMatch,
  type QuickAddResult,
  type SimilarityConfig,
  shouldRefreshToken,
  splitByBreaksPreservingFences,
  splitMessageByBreaks,
  type TokenStorage,
  truncateText,
} from "./utils";
export {
  BUILTIN_TRIGGER_META,
  type BuiltinTriggerMeta,
  buildDefaultTriggerConfig,
  findTriggerSchema,
  formatIntegrationLabel,
  getSchemaFieldEntries,
  getTriggerLogoKey,
  groupTriggerSchemasByIntegration,
  type IntegrationTriggerGroup,
  type TriggerFieldSchema,
  type TriggerSchema,
} from "./workflows";
