/**
 * GAIA Shared TypeScript Library
 *
 * Shared utilities for GAIA TypeScript/JavaScript applications.
 */

// `./analytics` is intentionally NOT re-exported here. It pulls in
// `posthog-node` which imports Node-only modules (`path`, `fs`) that
// Metro/React Native cannot resolve. Bot consumers should import it
// via the subpath: `import { Analytics } from "@gaia/shared/analytics"`.
export type {
  AddPublicIntegrationParams,
  AddToWorkspaceParams,
  ApiClientConfig,
  BatchSyncConversationsParams,
  BulkNotificationAction,
  BulkNotificationActionParams,
  ChatStreamFileData,
  ChatStreamMessage,
  ChatStreamParams,
  ChatStreamReplyTo,
  CommunityIntegrationsParams,
  ConnectIntegrationParams,
  ConnectParams,
  ConversationListParams,
  ConversationSyncItem,
  CreateCustomIntegrationParams,
  DisconnectParams,
  GenerateImageParams,
  IntegrationAddPublicResponse,
  IntegrationConnectResponse,
  IntegrationListParams,
  IntegrationPublishResponse,
  IntegrationStatusEntry,
  IntegrationStatusResponse,
  IntegrationUnpublishResponse,
  IntegrationWorkspaceAddResponse,
  McpTestConnectionResponse,
  NotificationListParams,
  NotificationReadStatusParams,
  NotificationStatusFilter,
  PinMessageParams,
  RenameConversationParams,
  SearchApi,
  SearchIntegrationsParams,
  SearchMode,
  SnoozeNotificationParams,
  StarConversationParams,
  SubtaskCreateParams,
  SubtaskUpdateParams,
  TestConnectionParams,
  TestNotificationParams,
  TodoBulkActionParams,
  TodoBulkMoveParams,
  TodoListParams,
  TodoSemanticSearchParams,
  UpdateChannelPreferenceParams,
  WorkflowCommunityParams,
  WorkflowCreateParams,
  WorkflowExecutionsParams,
  WorkflowFromTodoParams,
  WorkflowGeneratePromptParams,
  WorkflowListParams,
  WorkflowRegenerateParams,
  WorkflowTriggerOptionsParams,
  WorkflowUpdateParams,
} from "./api";

export {
  ApiError,
  buildIntegrationUrl,
  buildQueryString,
  buildSearchQuery,
  buildUrl,
  CONVERSATION_ENDPOINTS,
  createApiHeaders,
  INTEGRATION_ENDPOINTS,
  NOTIFICATION_ENDPOINTS,
  normalizeListResponse,
  SearchApiEndpoints,
  TODO_ENDPOINTS,
  WORKFLOW_ENDPOINTS,
} from "./api";
// `./bots` is intentionally NOT re-exported here. It pulls Node-only modules
// (`node:fs`, `dotenv`) that Metro/React Native cannot resolve. Bot consumers
// should import via the subpath: `import { allCommands } from "@gaia/shared/bots"`.

export type {
  ApiFileData,
  ApiToolData,
  ApprovalDecision,
  ApprovalDecisionPayload,
  ApprovalRequestData,
  ApprovalScope,
  ApprovalStatus,
  ArtifactData,
  BatchApprovalDecisionPayload,
  BatchApprovalDecisionResponse,
  BatchDecisionItem,
  BatchDecisionOutcome,
  CalendarDeleteOptions,
  CalendarEditOptions,
  CalendarEventDateTime,
  CalendarFetchData,
  CalendarListFetchData,
  CalendarOptions,
  ChatStreamEvent,
  CodeChartData,
  CodeData,
  CodeOutput,
  ContactData,
  Conversation,
  DeepResearchResults,
  DeepResearchSource,
  EmailComposeData,
  EmailFetchData,
  EmailSentData,
  EmailThreadData,
  EmailThreadMessage,
  EnhancedWebResult,
  GenericToolData,
  GoogleDocsData,
  GoogleDocsDocument,
  GroupedConversations,
  HilMode,
  HilPreferences,
  ImageResult,
  MCPAppData,
  NewsResult,
  PeopleSearchData,
  RateLimitData,
  RecurrenceData,
  RecurrenceRule,
  RedditCommentCreatedData,
  RedditCommentData,
  RedditData,
  RedditPostCreatedData,
  RedditPostData,
  RedditSearchData,
  ReplyToMessageData,
  SameDayEvent,
  SearchResults,
  SharedMemoryData,
  StreamToolDataEntry,
  StreamToolOutput,
  SubagentEndPayload,
  SubagentGroupData,
  SubagentStartPayload,
  TodoAction,
  TodoItem,
  TodoPriority,
  TodoProgressData,
  TodoProgressItem,
  TodoProgressSnapshot,
  TodoProgressStatus,
  TodoProject,
  TodoSubtask,
  TodoToolData,
  TodoToolStats,
  ToolCallEntry,
  ToolDataEntry,
  ToolDataMap,
  ToolFixture,
  ToolName,
  TurnAccumulator,
  TwitterData,
  TwitterFollowersData,
  TwitterPostCreatedData,
  TwitterPostPreviewData,
  TwitterSearchData,
  TwitterTimelineData,
  TwitterTweetData,
  TwitterUserData,
  WeatherData,
  WebResult,
  WorkflowCreatedData,
  WorkflowDraftData,
} from "./chat";
export {
  APPROVAL_REQUEST_TOOL_NAME,
  applyStreamEvent,
  approvalOutcomeLabel,
  createTurnAccumulator,
  DEFAULT_HIL_MODE,
  extractToolProgressMessage,
  getFixture,
  getToolData,
  isKnownTool,
  isSettled,
  mergeToolOutputIntoToolData,
  parseChatStreamEvent,
  REASONING_TOOL_NAME,
  SUBAGENT_GROUP_TOOL_NAME,
  TOOL_CALLS_DATA_TOOL_NAME,
  TOOL_FIXTURES,
  toolAsks,
  toolOverrideValue,
  updateSubagentInToolData,
  upsertApprovalToolData,
  upsertTodoProgressToolData,
} from "./chat";
export {
  CLI_COMMAND_DESCRIPTIONS,
  CLI_INSTALL_COMMANDS,
} from "./cli";
export {
  USAGE_DANGER_THRESHOLD,
  USAGE_WARN_THRESHOLD,
} from "./constants/usage";
export type {
  DesktopAppIconOption,
  DesktopMediaAccessStatus,
  DesktopPermissionPane,
  DesktopPermissionStatus,
  DesktopScreenshotData,
  DesktopSettings,
  DesktopSettingsSnapshot,
  DesktopShortcutUpdateResult,
  DesktopToolName,
  DesktopToolRequest,
  DesktopToolResult,
  DesktopWindowInfo,
} from "./desktop-tools";
export {
  DESKTOP_TOOL_DEFAULT_TIMEOUT_MS,
  DESKTOP_TOOL_NAMES,
  isDesktopToolName,
} from "./desktop-tools";
export type {
  IntegrationStatusDisplay,
  NotificationFilter,
  TodoFilterState,
  WorkflowFilterState,
} from "./hooks";
export {
  categorizeIntegrations,
  filterIntegrations,
  filterNotifications,
  filterTodos,
  filterWorkflows,
  getIntegrationDisplayStatus,
  getNotificationIcon,
  groupNotificationsByDate,
  groupTodosByDate,
  groupTodosByProject,
  IntegrationQueryKeys,
  NotificationQueryKeys,
  sortTodos,
  sortWorkflows,
  TodoQueryKeys,
  WorkflowQueryKeys,
} from "./hooks";
export type {
  CreateTodoStoreOptions,
  HttpAdapter,
  NotifyAdapter,
  RequestOptions,
  SemanticSearchOptions,
  TodoApiClient,
  TodoStore,
  TodoStoreHook,
  WorkflowGenerateResult,
  WorkflowStatusCacheEntry,
  WorkflowStatusResult,
} from "./todos";
export {
  buildWorkflowStatusEntry,
  createTodoApi,
  createTodoStore,
  isWorkflowStatusFresh,
  WORKFLOW_STATUS_TTL_MS,
  WORKFLOW_WS_EVENTS,
} from "./todos";
export {
  bucketDate,
  formatAllDayDate,
  formatAllDayDateRange,
  formatDateWithRelative,
  formatTimedEventDate,
  formatTimeRange,
  formatTimeString,
  formatToolDueDate,
  getEventDurationText,
  groupEventsByDate,
  isDateOnly,
} from "./tool-utils";
export type {
  ActivityDay,
  BudgetWindow,
  BulkMoveRequest,
  ChannelPlatform,
  ChannelPreferences,
  CommunityIntegration,
  CommunityIntegrationsResponse,
  CommunitySearchParams,
  CommunityWorkflow,
  ContentCreator,
  CreateCustomIntegrationRequest,
  CreateWorkflowPayload,
  CronValidationResult,
  DiscoverSkillsResponse,
  ExecutionConfig,
  FeatureUsage,
  FileData,
  FileUploadResult,
  ImageData,
  InAppNotification,
  InAppNotificationContent,
  Integration,
  IntegrationAuthType,
  IntegrationCategory,
  IntegrationConnectionData,
  IntegrationCreator,
  IntegrationManagedBy,
  IntegrationStatusRecord,
  IntegrationStatusValue,
  IntegrationTool,
  IntegrationToolsResponse,
  LLMModel,
  MarketplaceIntegration,
  Memory,
  MemoryCreate,
  MemorySearchParams,
  MemorySearchResponse,
  MyIntegrationItem,
  MyIntegrationsResponse,
  Note,
  NoteCreate,
  NoteListResponse,
  NoteUpdate,
  NotificationAction,
  NotificationActionConfig,
  PaginationMeta,
  PlatformLink,
  PlatformLinksResponse,
  Project,
  ProjectCreate,
  ProjectUpdate,
  PublicIntegrationResponse,
  QuietHours,
  Reminder,
  ReminderCreate,
  ReminderStatus,
  ReminderUpdate,
  SearchConversationResult,
  SearchMessageResult,
  SearchNoteResult,
  SearchParams,
  SearchResponse,
  SearchResult,
  Skill,
  SkillCreate,
  SkillStatus,
  SkillTool,
  SubTask,
  Todo,
  TodoCounts,
  TodoCreate,
  TodoFilters,
  TodoLabel,
  TodoListResponse,
  TodoUpdate,
  Tool,
  ToolCategory,
  ToolsByCategoryResponse,
  ToolsListResponse,
  TriggerConfig,
  UsageActivity,
  UsageBudget,
  UsagePeriod,
  UsageSummary,
  UserIntegration,
  Workflow,
  WorkflowListResponse,
  WorkflowMetadata,
  WorkflowResponse,
  WorkflowStep,
} from "./types";
export {
  DEFAULT_MODELS,
  FileType,
  getFileType,
  getModelById,
  getModelsByProvider,
  MODEL_ENDPOINTS,
  ModelProvider,
  NotificationActionStyle,
  NotificationActionType,
  NotificationStatus,
  Priority,
  WorkflowStatus,
} from "./types";
export type {
  ContentSegment,
  DueChipTone,
  IntegrationConnectionState,
  JwtPayload,
  OpenUIActionEventLike,
  OpenUIActionHandlers,
  OpenUILibraryLike,
  OpenUISample,
  ParsedContent,
  QuickAddOptions,
  QuickAddProject,
  QuickAddProjectMatch,
  QuickAddResult,
  SimilarityConfig,
  TokenStorage,
} from "./utils";
export {
  CONNECT_ACTION_LABEL,
  connectionPromptState,
  DEFAULT_SIMILARITY_CONFIG,
  dispatchOpenUIAction,
  extractUrls,
  formatCompactNumber,
  formatCurrency,
  formatDate,
  formatDateUTC,
  formatDueDate,
  formatDuration,
  formatFeatureName,
  formatFileSize,
  formatNumber,
  formatPlanName,
  formatRelativeDate,
  formatRelativeTime,
  formatRunCount,
  getCompleteTimeBasedGreeting,
  getDueChipTone,
  getRandomThinkingMessage,
  getRelevantLoadingMessage,
  getRelevantThinkingMessage,
  getSimpleTimeGreeting,
  getTriggerLabel,
  INTEGRATION_STATE_ORDER,
  integrationConnectionState,
  isOverdue,
  isTokenExpired,
  NEW_MESSAGE_BREAK_TOKEN,
  NEW_MESSAGE_BREAK_TOKEN_LENGTH,
  normalizeOpenUICode,
  OPENUI_SAMPLES,
  PLAYFUL_THINKING_MESSAGES,
  parseCronToHuman,
  parseJwt,
  parseOpenUISegments,
  parseQuickAdd,
  parseRelativeDateLabel,
  parseThinkingFromText,
  shouldRefreshToken,
  splitMessageByBreaks,
  truncateText,
} from "./utils";
export type {
  BuiltinTriggerMeta,
  IntegrationTriggerGroup,
  TriggerFieldSchema,
  TriggerSchema,
} from "./workflows";
export {
  BUILTIN_TRIGGER_META,
  buildDefaultTriggerConfig,
  findTriggerSchema,
  formatIntegrationLabel,
  getSchemaFieldEntries,
  getTriggerLogoKey,
  groupTriggerSchemasByIntegration,
} from "./workflows";
