"""Tests for openui_prompts — spec-driven, independent of implementation details."""

import pathlib

import pytest

_GENERATED_PROMPT_PATH = (
    pathlib.Path(__file__).parent.parent / "app" / "agents" / "prompts" / "openui_generated.txt"
)


def test_generated_prompt_artifact_exists_and_nonempty():
    """The component vocabulary is generated by `pnpm openui:gen-prompt`.

    A pre-commit hook regenerates it on change, so it must always be present
    and substantial. Regenerate with `pnpm openui:gen-prompt` if this fails.
    """
    assert _GENERATED_PROMPT_PATH.exists(), (
        f"{_GENERATED_PROMPT_PATH} missing — run `pnpm openui:gen-prompt`"
    )
    content = _GENERATED_PROMPT_PATH.read_text(encoding="utf-8")
    assert len(content) > 500, "generated openui prompt is suspiciously short"


def test_suppressed_tools_match_tool_fields():
    from app.agents.prompts.openui_prompts import OPENUI_SUPPRESSED_TOOLS
    from app.models.chat_models import tool_fields

    for tool in tool_fields:
        assert tool in OPENUI_SUPPRESSED_TOOLS, f"{tool} missing from OPENUI_SUPPRESSED_TOOLS"


def test_no_extra_suppressed_tools():
    from app.agents.prompts.openui_prompts import OPENUI_SUPPRESSED_TOOLS
    from app.models.chat_models import tool_fields

    tool_fields_set = set(tool_fields)
    for tool in OPENUI_SUPPRESSED_TOOLS:
        assert tool in tool_fields_set, f"{tool} in OPENUI_SUPPRESSED_TOOLS but not in tool_fields"


def test_instructions_renders_each_suppressed_tool():
    from app.agents.prompts.openui_prompts import (
        OPENUI_INSTRUCTIONS,
        OPENUI_SUPPRESSED_TOOLS,
    )

    for tool in OPENUI_SUPPRESSED_TOOLS:
        assert tool in OPENUI_INSTRUCTIONS, f"Tool {tool} not mentioned in OPENUI_INSTRUCTIONS"


def test_instructions_contains_stable_component_anchors():
    """A handful of stable, load-bearing components must always be documented.

    These anchors come from both the official react-ui library (Stack, Table,
    BarChart) and GAIA's own components (GaugeChart, MapBlock, Timeline,
    TextDocument, CopyableContent). Full coverage is enforced by the generator;
    this is a smoke check that the merged vocabulary made it into the prompt.
    """
    from app.agents.prompts.openui_prompts import OPENUI_INSTRUCTIONS

    anchors = [
        # react-ui library
        "Stack",
        "Card",
        "Table",
        "BarChart",
        "Steps",
        # GAIA-only
        "GaugeChart",
        "MapBlock",
        "Timeline",
        "TextDocument",
        "CopyableContent",
    ]
    for name in anchors:
        assert name in OPENUI_INSTRUCTIONS, (
            f"Component {name} not documented in OPENUI_INSTRUCTIONS"
        )


def test_instructions_contains_surface_policy():
    from app.agents.prompts.openui_prompts import OPENUI_INSTRUCTIONS

    assert "SURFACE POLICY" in OPENUI_INSTRUCTIONS


def test_instructions_is_nonempty_string():
    from app.agents.prompts.openui_prompts import OPENUI_INSTRUCTIONS

    assert isinstance(OPENUI_INSTRUCTIONS, str)
    assert len(OPENUI_INSTRUCTIONS) > 500


def test_suppressed_tools_is_list_of_strings():
    from app.agents.prompts.openui_prompts import OPENUI_SUPPRESSED_TOOLS

    assert isinstance(OPENUI_SUPPRESSED_TOOLS, list)
    for item in OPENUI_SUPPRESSED_TOOLS:
        assert isinstance(item, str)


def test_enable_openui_removed_from_settings():
    """
    Verify ENABLE_OPENUI is not defined in any settings class.
    Uses AST parsing to avoid triggering the module-level get_settings() call
    which requires live Infisical credentials.
    """
    import ast

    settings_path = pathlib.Path(__file__).parent.parent / "app" / "config" / "settings.py"
    source = settings_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(settings_path))

    for node in ast.walk(tree):
        # Check annotated assignments (e.g. ENABLE_OPENUI: bool = True)
        if isinstance(node, ast.AnnAssign):
            target = node.target
            if isinstance(target, ast.Name) and target.id == "ENABLE_OPENUI":
                pytest.fail(
                    "ENABLE_OPENUI annotated field found in settings.py — it should have been removed"
                )
        # Check plain assignments (e.g. ENABLE_OPENUI = True)
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "ENABLE_OPENUI":
                    pytest.fail(
                        "ENABLE_OPENUI assignment found in settings.py — it should have been removed"
                    )
