"""Export the event catalog to analytics-catalog.json and the TypeScript event types.

Run through `mise analytics:types`; CI regenerates both and fails on any diff.
"""

from enum import Enum
import json
from pathlib import Path
import types
from typing import Annotated, Literal, Union, get_args, get_origin

from pydantic.fields import FieldInfo

from shared.py.analytics.catalog import CATALOG
from shared.py.analytics.catalog.base import AnalyticsEvent, Surface

GENERATED_DIR = Path(__file__).resolve().parents[2] / "ts" / "src" / "analytics" / "generated"
CATALOG_JSON = GENERATED_DIR / "analytics-catalog.json"
EVENTS_TS = GENERATED_DIR / "events.d.ts"

_TS_SCALARS: dict[type, str] = {bool: "boolean", int: "number", float: "number", str: "string"}
_NAME_UNIONS: dict[Surface, str] = {
    Surface.SERVER: "ServerEventName",
    Surface.WEB: "WebEventName",
    Surface.BOT: "BotEventName",
    Surface.VOICE: "VoiceEventName",
}


def _ts_literal(value: object) -> str:
    return json.dumps(value)


def _ts_type(annotation: object) -> str:
    """Render a catalog property annotation (already validated by the base class) as TypeScript."""
    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return " | ".join(_ts_literal(member.value) for member in annotation)
    if isinstance(annotation, type):
        return _TS_SCALARS[annotation]
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Annotated:
        return _ts_type(args[0])
    if origin is Literal:
        return " | ".join(_ts_literal(arg) for arg in args)
    if origin in (Union, types.UnionType):
        return " | ".join(_ts_type(arg) for arg in args if arg is not type(None))
    if (origin is tuple and len(args) == 2 and args[1] is Ellipsis) or origin in (list, frozenset):
        return f"({_ts_type(args[0])})[]"
    if origin is tuple:
        return "[" + ", ".join(_ts_type(arg) for arg in args) + "]"
    raise TypeError(f"no TypeScript rendering for {annotation!r}")


def _ts_property(name: str, field: FieldInfo) -> str:
    optional = "" if field.is_required() else "?"
    return f"    {json.dumps(name)}{optional}: {_ts_type(field.annotation)};"


def _ts_properties(model: type[AnalyticsEvent]) -> str:
    fields = {
        **(model.base_properties.model_fields if model.base_properties is not None else {}),
        **model.model_fields,
    }
    if not fields:
        return "Record<string, never>"
    lines = [_ts_property(name, field) for name, field in fields.items()]
    return "{\n" + "\n".join(lines) + "\n  }"


def render_typescript() -> str:
    """Render the event-name unions per surface and the EventProperties map."""
    out = [
        "// Generated by `mise analytics:types` from libs/shared/py/analytics/catalog. Do not edit.",
        "",
    ]
    for surface, union in _NAME_UNIONS.items():
        names = [name for name, model in CATALOG.items() if model.owner is surface]
        body = "".join(f"\n  | {_ts_literal(name)}" for name in names) or " never"
        out.append(f"export type {union} ={body};\n")
    out.append("export type AnalyticsEventName = " + " | ".join(_NAME_UNIONS.values()) + ";\n")
    out.append("export interface EventProperties {")
    for name, model in CATALOG.items():
        out.append(f"  {_ts_literal(name)}: {_ts_properties(model)};")
    out.append("}\n")
    return "\n".join(out)


def export_catalog() -> dict[str, object]:
    """Describe every event (owner, domain, rename history, budget, gate, properties) and the base schemas."""
    bases = {model.base_properties for model in CATALOG.values() if model.base_properties}
    return {
        "base_properties": {
            base.__name__: base.model_json_schema()
            for base in sorted(bases, key=lambda b: b.__name__)
        },
        "events": [
            {
                "event": name,
                "class": model.__name__,
                "owner": model.owner.value,
                "domain": name.split(":", 1)[0],
                "description": (model.__doc__ or "").strip(),
                "previous_names": list(model.previous_names),
                "budget_per_user_day": model.budget_per_user_day,
                "at_most_once_ttl_seconds": (
                    int(model.at_most_once_ttl.total_seconds())
                    if model.at_most_once_ttl is not None
                    else None
                ),
                "base_properties": (
                    model.base_properties.__name__ if model.base_properties is not None else None
                ),
                "properties": model.model_json_schema(),
            }
            for name, model in CATALOG.items()
        ],
    }


def main() -> None:
    """Write both generated artifacts."""
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    CATALOG_JSON.write_text(json.dumps(export_catalog(), indent=2) + "\n", encoding="utf-8")
    EVENTS_TS.write_text(render_typescript(), encoding="utf-8")


if __name__ == "__main__":
    main()
