<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title>GAIA Sitemap Index</title>
        <meta name="robots" content="noindex, follow"/>
        <style type="text/css">
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a2e; background: #fafafa; }
          .container { max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem; }
          .header { margin-bottom: 2rem; }
          .header h1 { font-size: 1.5rem; font-weight: 600; margin-bottom: 0.25rem; }
          .header p { color: #6b7280; font-size: 0.875rem; }
          .count { display: inline-block; background: #e0e7ff; color: #3730a3; font-size: 0.75rem; font-weight: 600; padding: 0.15rem 0.5rem; border-radius: 9999px; margin-left: 0.5rem; vertical-align: middle; }
          table { width: 100%; border-collapse: collapse; background: #fff; border-radius: 0.5rem; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
          th { text-align: left; padding: 0.75rem 1rem; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; color: #6b7280; background: #f9fafb; border-bottom: 1px solid #e5e7eb; }
          td { padding: 0.75rem 1rem; font-size: 0.875rem; border-bottom: 1px solid #f3f4f6; }
          tr:last-child td { border-bottom: none; }
          tr:hover td { background: #f9fafb; }
          a { color: #4f46e5; text-decoration: none; }
          a:hover { text-decoration: underline; }
          .footer { margin-top: 1.5rem; font-size: 0.75rem; color: #9ca3af; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Sitemap Index
              <span class="count"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps</span>
            </h1>
            <p>This sitemap index contains links to all GAIA sub-sitemaps.</p>
          </div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>Sitemap URL</th>
                <th>Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                <tr>
                  <td><xsl:value-of select="position()"/></td>
                  <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                  <td><xsl:value-of select="substring(sitemap:lastmod, 1, 10)"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
          <div class="footer">Generated by GAIA &#x2022; <a href="https://heygaia.io">heygaia.io</a></div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
