packages:
  - apps/*
  - apps/bots/*
  - packages/*
  - libs/*
  - libs/shared/*

onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - "@parcel/watcher"
  - "@sentry/cli"
  - canvas
  - core-js
  - electron
  - esbuild
  - nx
  - sharp
