"""
OAuth Integration Configuration

Single source of truth for all OAuth integration configurations in GAIA.
Defines integrations, scopes, display properties, and subagent configurations.
"""

from functools import cache
from typing import Dict, List, Optional


from app.agents.prompts.subagent_prompts import (
    AIRTABLE_AGENT_SYSTEM_PROMPT,
    ASANA_AGENT_SYSTEM_PROMPT,
    CALENDAR_AGENT_SYSTEM_PROMPT,
    CLICKUP_AGENT_SYSTEM_PROMPT,
    CONTEXT7_AGENT_SYSTEM_PROMPT,
    DEEPWIKI_AGENT_SYSTEM_PROMPT,
    GITHUB_AGENT_SYSTEM_PROMPT,
    GMAIL_AGENT_SYSTEM_PROMPT,
    GOALS_AGENT_SYSTEM_PROMPT,
    GOOGLE_MAPS_AGENT_SYSTEM_PROMPT,
    GOOGLE_MEET_AGENT_SYSTEM_PROMPT,
    GOOGLE_SHEETS_AGENT_SYSTEM_PROMPT,
    GOOGLE_TASKS_AGENT_SYSTEM_PROMPT,
    HUBSPOT_AGENT_SYSTEM_PROMPT,
    INSTAGRAM_AGENT_SYSTEM_PROMPT,
    LINEAR_AGENT_SYSTEM_PROMPT,
    LINKEDIN_AGENT_SYSTEM_PROMPT,
    NOTION_AGENT_SYSTEM_PROMPT,
    PERPLEXITY_AGENT_SYSTEM_PROMPT,
    REDDIT_AGENT_SYSTEM_PROMPT,
    REMINDER_AGENT_SYSTEM_PROMPT,
    SLACK_AGENT_SYSTEM_PROMPT,
    TODO_AGENT_SYSTEM_PROMPT,
    TODOIST_AGENT_SYSTEM_PROMPT,
    TRELLO_AGENT_SYSTEM_PROMPT,
    TWITTER_AGENT_SYSTEM_PROMPT,
)
from app.langchain.core.subgraphs.github_subgraph import GITHUB_TOOLS
from app.models.oauth_models import (
    ComposioConfig,
    MCPConfig,
    OAuthIntegration,
    OAuthScope,
    ProviderMetadataConfig,
    SubAgentConfig,
    TriggerConfig,
)


# Define all integrations dynamically
OAUTH_INTEGRATIONS: List[OAuthIntegration] = [
    # Individual Google integrations
    OAuthIntegration(
        id="google_calendar",
        name="Google Calendar",
        description="Schedule meetings and manage your calendar events",
        category="productivity",
        provider="google",
        scopes=[
            OAuthScope(
                scope="https://www.googleapis.com/auth/calendar.events",
                description="Create and manage calendar events",
            ),
            OAuthScope(
                scope="https://www.googleapis.com/auth/calendar.readonly",
                description="View calendar events",
            ),
        ],
        is_featured=True,
        short_name="calendar",
        managed_by="self",
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="google_calendar_agent",
            tool_space="google_calendar",
            handoff_tool_name="call_calendar_agent",
            domain="calendar and event management",
            capabilities="creating events, scheduling meetings, managing availability, setting reminders, updating calendar entries, and organizing schedules",
            use_cases="scheduling meetings, managing calendar events, checking availability, or any calendar-related task",
            system_prompt=CALENDAR_AGENT_SYSTEM_PROMPT,
            use_direct_tools=True,
            disable_retrieve_tools=True,
        ),
    ),
    OAuthIntegration(
        id="google_docs",
        name="Google Docs",
        description="Create and edit documents in your workspace",
        category="productivity",
        provider="google",
        scopes=[
            OAuthScope(
                scope="https://www.googleapis.com/auth/documents",
                description="Create and edit documents",
            ),
        ],
        short_name="docs",
        managed_by="self",
    ),
    # Internal Todo System (no OAuth required)
    OAuthIntegration(
        id="todos",
        name="Todos",
        description="Manage tasks, projects, and personal productivity with AI assistance",
        category="productivity",
        provider="todos",
        scopes=[],
        available=True,
        is_featured=False,
        short_name="todos",
        managed_by="internal",
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="todo_agent",
            tool_space="todos",
            handoff_tool_name="call_todo_agent",
            domain="task and productivity management",
            capabilities="creating todos, managing tasks, organizing projects, tracking priorities, setting due dates, using labels, bulk operations, searching tasks, and providing productivity insights",
            use_cases="managing personal todos, organizing tasks by project, tracking deadlines, bulk task operations, or any productivity-related task",
            system_prompt=TODO_AGENT_SYSTEM_PROMPT,
            use_direct_tools=True,
            disable_retrieve_tools=True,
        ),
    ),
    # Internal Reminders System (no OAuth required)
    OAuthIntegration(
        id="reminders",
        name="Reminders",
        description="Schedule time-based reminders with AI assistance",
        category="productivity",
        provider="reminders",
        scopes=[],
        available=True,
        is_featured=False,
        short_name="reminders",
        managed_by="internal",
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="reminder_agent",
            tool_space="reminders",
            handoff_tool_name="call_reminder_agent",
            domain="scheduling and time-based notifications",
            capabilities="creating reminders, scheduling notifications, setting recurring reminders, managing reminder statuses, searching reminders",
            use_cases="scheduling reminders, setting up recurring notifications, managing time-based alerts, or any reminder-related task",
            system_prompt=REMINDER_AGENT_SYSTEM_PROMPT,
            use_direct_tools=True,
            disable_retrieve_tools=True,
        ),
    ),
    # Internal Goals System (no OAuth required)
    OAuthIntegration(
        id="goals",
        name="Goals",
        description="Track long-term goals and roadmaps with AI assistance",
        category="productivity",
        provider="goals",
        scopes=[],
        available=True,
        is_featured=False,
        short_name="goals",
        managed_by="internal",
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="goals_agent",
            tool_space="goals",
            handoff_tool_name="call_goals_agent",
            domain="long-term goal planning and progress tracking",
            capabilities="creating goals, generating roadmaps, tracking progress, managing goal nodes, searching goals, viewing goal statistics",
            use_cases="setting long-term goals, generating action roadmaps, tracking goal progress, or any goal-related task",
            system_prompt=GOALS_AGENT_SYSTEM_PROMPT,
            use_direct_tools=True,
            disable_retrieve_tools=True,
        ),
    ),
    OAuthIntegration(
        id="gmail",
        name="Gmail",
        description="Manage emails, compose messages, and organize your inbox",
        category="communication",
        provider="gmail",
        scopes=[
            OAuthScope(
                scope="https://www.googleapis.com/auth/gmail.modify",
                description="Read, compose, and send emails",
            )
        ],
        is_featured=True,
        short_name="gmail",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_svLPDmjcTVMX", toolkit="GMAIL"
        ),
        associated_triggers=[
            TriggerConfig(
                slug="GMAIL_NEW_GMAIL_MESSAGE",
                name="New Gmail Message",
                description="Triggered when a new Gmail message arrives",
                config={"labelIds": "INBOX", "user_id": "me", "interval": 1},
            )
        ],
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="gmail_agent",
            tool_space="gmail",
            handoff_tool_name="call_gmail_agent",
            domain="email",
            capabilities="composing emails, sending messages, reading inbox, organizing with labels, managing drafts, handling attachments, searching emails, and automating email workflows",
            use_cases="any email-related task including sending, reading, organizing, or automating email operations",
            system_prompt=GMAIL_AGENT_SYSTEM_PROMPT,
        ),
    ),
    # Notion MCP (OAuth with pre-registered client)
    OAuthIntegration(
        id="notion",
        name="Notion",
        description="Manage pages, databases, and workspace content with AI assistance.",
        category="productivity",
        provider="notion",
        scopes=[],
        available=True,
        is_featured=True,
        short_name="notion",
        managed_by="mcp",
        mcp_config=MCPConfig(
            server_url="https://mcp.notion.com/sse",
            requires_auth=True,
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="notion_agent",
            tool_space="notion",
            handoff_tool_name="call_notion_agent",
            domain="workspace and knowledge management",
            capabilities="creating pages, building databases, updating content, organizing workspaces, managing properties, searching content, and structuring knowledge bases",
            use_cases="creating pages, managing databases, organizing knowledge, or any Notion workspace operation",
            system_prompt=NOTION_AGENT_SYSTEM_PROMPT,
        ),
    ),
    # OLD Composio Notion (commented out - using MCP now)
    # OAuthIntegration(
    #     id="notion",
    #     name="Notion",
    #     description="Manage pages, databases, and workspace content",
    #     category="productivity",
    #     provider="notion",
    #     scopes=[],
    #     available=True,
    #     is_featured=True,
    #     short_name="notion",
    #     managed_by="composio",
    #     composio_config=ComposioConfig(
    #         auth_config_id="ac_DR3IWp9-Kezl",
    #         toolkit="NOTION",
    #     ),
    #     subagent_config=SubAgentConfig(
    #         has_subagent=True,
    #         agent_name="notion_agent",
    #         tool_space="notion",
    #         handoff_tool_name="call_notion_agent",
    #         domain="workspace and knowledge management",
    #         capabilities="creating pages, building databases, updating content, organizing workspaces, managing properties, searching content, and structuring knowledge bases",
    #         use_cases="creating pages, managing databases, organizing knowledge, or any Notion workspace operation",
    #         system_prompt=NOTION_AGENT_SYSTEM_PROMPT,
    #     ),
    # ),
    OAuthIntegration(
        id="twitter",
        name="Twitter",
        description="Post tweets, read timelines, and manage your account",
        category="social_media",
        provider="twitter",
        scopes=[],
        available=True,
        short_name="twitter",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_vloH3fnhIeUa",
            toolkit="TWITTER",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="twitter_agent",
            tool_space="twitter",
            handoff_tool_name="call_twitter_agent",
            domain="social media",
            capabilities="posting tweets, creating threads, replying to posts, liking content, retweeting, following users, analyzing engagement metrics, and managing Twitter presence",
            use_cases="posting tweets, engaging with content, managing followers, or analyzing Twitter activity",
            system_prompt=TWITTER_AGENT_SYSTEM_PROMPT,
        ),
        metadata_config=ProviderMetadataConfig(
            user_info_tool="TWITTER_USER_LOOKUP_ME",
            username_field="data.data.username",
        ),
    ),
    OAuthIntegration(
        id="googlesheets",
        name="Google Sheets",
        description="Create, read, and update spreadsheets",
        category="productivity",
        provider="googlesheets",
        scopes=[],
        available=True,
        short_name="sheets",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_18I3fRfWyXDu",
            toolkit="GOOGLESHEETS",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="google_sheets_agent",
            tool_space="googlesheets",
            handoff_tool_name="call_google_sheets_agent",
            domain="spreadsheet management and data analysis",
            capabilities="creating spreadsheets, updating data, managing formulas, organizing sheets, analyzing data, and building collaborative workbooks",
            use_cases="spreadsheet management, data analysis, formula creation, or any Google Sheets operation",
            system_prompt=GOOGLE_SHEETS_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="linkedin",
        name="LinkedIn",
        description="Share posts and engage with your professional network",
        category="social_media",
        provider="linkedin",
        scopes=[],
        available=True,
        short_name="linkedin",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_GMeJBELf3z_m",
            toolkit="LINKEDIN",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="linkedin_agent",
            tool_space="linkedin",
            handoff_tool_name="call_linkedin_agent",
            domain="professional networking",
            capabilities="creating professional posts, managing connections, networking outreach, updating profile, engaging with content, job searching, and building professional presence",
            use_cases="posting professional content, managing connections, networking, or any LinkedIn career-related activity",
            system_prompt=LINKEDIN_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="github",
        name="GitHub",
        is_featured=True,
        description="Manage repositories, issues, pull requests, and automate your development workflow",
        category="developer",
        provider="github",
        scopes=[],
        available=True,
        short_name="github",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_y2VK4j0ATiZo",
            toolkit="GITHUB",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="github_agent",
            tool_space="github",
            handoff_tool_name="call_github_agent",
            domain="code repository and development workflow",
            capabilities="managing repositories, creating issues, handling pull requests, managing branches, reviewing code, managing collaborators, and automating development workflows",
            use_cases="repository management, issue tracking, pull requests, code review, or any GitHub development task",
            system_prompt=GITHUB_AGENT_SYSTEM_PROMPT,
            specific_tools=GITHUB_TOOLS,
        ),
        metadata_config=ProviderMetadataConfig(
            user_info_tool="GITHUB_GET_THE_AUTHENTICATED_USER",
            username_field="data.login",
        ),
    ),
    OAuthIntegration(
        id="reddit",
        name="Reddit",
        description="Post content, manage comments, and engage with communities on Reddit",
        category="social_media",
        provider="reddit",
        scopes=[],
        available=True,
        short_name="reddit",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_7-hfiMVLhcDN",
            toolkit="REDDIT",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="reddit_agent",
            tool_space="reddit",
            handoff_tool_name="call_reddit_agent",
            domain="community engagement and content sharing",
            capabilities="posting content, commenting on posts, managing subreddits, searching communities, voting on content, and engaging with Reddit communities",
            use_cases="posting to Reddit, engaging with communities, managing subreddit content, or analyzing Reddit activity",
            system_prompt=REDDIT_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="airtable",
        name="Airtable",
        description="Create and manage bases, tables, and records with AI-powered automation",
        category="business",
        provider="airtable",
        scopes=[],
        available=True,
        short_name="airtable",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_QPtQsXnIYm4C",
            toolkit="AIRTABLE",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="airtable_agent",
            tool_space="airtable",
            handoff_tool_name="call_airtable_agent",
            domain="database and workflow management",
            capabilities="creating bases, managing tables, updating records, organizing data, building automations, and structuring collaborative databases",
            use_cases="managing Airtable bases, organizing data, creating records, or building database workflows",
            system_prompt=AIRTABLE_AGENT_SYSTEM_PROMPT,
        ),
    ),
    # Linear MCP (OAuth via MCP spec discovery)
    OAuthIntegration(
        id="linear",
        name="Linear",
        description="Manage issues, projects, and track development progress with AI assistance",
        category="developer",
        provider="linear",
        scopes=[],
        available=True,
        short_name="linear",
        managed_by="mcp",
        mcp_config=MCPConfig(
            server_url="https://mcp.linear.app/sse",
            requires_auth=True,
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="linear_agent",
            tool_space="linear",
            handoff_tool_name="call_linear_agent",
            domain="issue tracking and project management",
            capabilities="creating issues, managing projects, tracking progress, assigning tasks, organizing sprints, and automating development workflows",
            use_cases="issue management, project tracking, sprint planning, or any Linear development workflow task",
            system_prompt=LINEAR_AGENT_SYSTEM_PROMPT,
            use_direct_tools=True,
        ),
    ),
    # OLD Composio Linear (commented out - using MCP now)
    # OAuthIntegration(
    #     id="linear",
    #     name="Linear",
    #     description="Manage issues, projects, and track development progress with AI assistance",
    #     category="developer",
    #     provider="linear",
    #     scopes=[],
    #     available=True,
    #     short_name="linear",
    #     managed_by="composio",
    #     composio_config=ComposioConfig(
    #         auth_config_id="ac_mnrcEhhTXPVS",
    #         toolkit="LINEAR",
    #     ),
    #     subagent_config=SubAgentConfig(
    #         has_subagent=True,
    #         agent_name="linear_agent",
    #         tool_space="linear",
    #         handoff_tool_name="call_linear_agent",
    #         domain="issue tracking and project management",
    #         capabilities="creating issues, managing projects, tracking progress, assigning tasks, organizing sprints, and automating development workflows",
    #         use_cases="issue management, project tracking, sprint planning, or any Linear development workflow task",
    #         system_prompt=LINEAR_AGENT_SYSTEM_PROMPT,
    #     ),
    # ),
    OAuthIntegration(
        id="slack",
        name="Slack",
        description="Send messages, manage channels, and automate team communication",
        category="communication",
        provider="slack",
        scopes=[],
        available=True,
        is_featured=True,
        short_name="slack",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_acm0K6K_kWxY",
            toolkit="SLACK",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="slack_agent",
            tool_space="slack",
            handoff_tool_name="call_slack_agent",
            domain="team communication and collaboration",
            capabilities="sending messages, managing channels, organizing conversations, sharing files, setting reminders, and automating team communication workflows",
            use_cases="sending Slack messages, managing channels, team communication, or automating workspace workflows",
            system_prompt=SLACK_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="hubspot",
        name="HubSpot",
        description="Manage CRM contacts, deals, and automate sales and marketing workflows",
        category="business",
        provider="hubspot",
        scopes=[],
        available=True,
        short_name="hubspot",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_rcnwYp1PRCVr",
            toolkit="HUBSPOT",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="hubspot_agent",
            tool_space="hubspot",
            handoff_tool_name="call_hubspot_agent",
            domain="CRM and sales automation",
            capabilities="managing contacts, tracking deals, organizing pipelines, automating marketing, managing customer relationships, and analyzing sales data",
            use_cases="CRM management, sales tracking, contact organization, or marketing automation tasks",
            system_prompt=HUBSPOT_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="googletasks",
        name="Google Tasks",
        description="Create, manage, and organize your tasks and to-do lists",
        category="productivity",
        provider="googletasks",
        scopes=[],
        available=True,
        short_name="tasks",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_xPSnVjKyHCDb",
            toolkit="GOOGLETASKS",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="google_tasks_agent",
            tool_space="googletasks",
            handoff_tool_name="call_google_tasks_agent",
            domain="task and to-do list management",
            capabilities="creating tasks, organizing to-do lists, managing task lists, setting due dates, marking tasks complete, and organizing personal productivity",
            use_cases="managing tasks, organizing to-do lists, tracking personal productivity, or any Google Tasks operation",
            system_prompt=GOOGLE_TASKS_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="todoist",
        name="Todoist",
        description="Manage tasks, projects, and productivity workflows with advanced task management",
        category="productivity",
        provider="todoist",
        scopes=[],
        available=True,
        short_name="todoist",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_TOjltL3O2kEB",
            toolkit="TODOIST",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="todoist_agent",
            tool_space="todoist",
            handoff_tool_name="call_todoist_agent",
            domain="task and project management",
            capabilities="creating tasks, organizing projects, setting priorities, managing labels, tracking productivity, and building task workflows",
            use_cases="task management, project organization, productivity tracking, or any Todoist operation",
            system_prompt=TODOIST_AGENT_SYSTEM_PROMPT,
        ),
    ),
    # OAuthIntegration(
    #     id="microsoft_teams",
    #     name="Microsoft Teams",
    #     description="Collaborate with teams, send messages, manage channels, and automate team workflows",
    #     category="communication",
    #     provider="microsoft_teams",
    #     scopes=[],
    #     available=True,
    #     short_name="teams",
    #     managed_by="composio",
    #     composio_config=ComposioConfig(
    #         auth_config_id="ac_0kzvAbsi2xu3", toolkit="MICROSOFTTEAMS"
    #     ),
    # ),
    # OAuthIntegration(
    #     id="zoom",
    #     name="Zoom",
    #     description="Create and manage Zoom meetings, webinars, and video conferencing",
    #     category="communication",
    #     provider="zoom",
    #     scopes=[],
    #     available=True,
    #     short_name="zoom",
    #     managed_by="composio",
    #     composio_config=ComposioConfig(
    #         auth_config_id="ac_fABNBG17lf2A", toolkit="ZOOM"
    #     ),
    # ),
    OAuthIntegration(
        id="googlemeet",
        name="Google Meet",
        description="Schedule and manage video meetings with Google Meet",
        category="communication",
        provider="googlemeet",
        scopes=[],
        available=True,
        short_name="meet",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_GsHKAmsiGvz1",
            toolkit="GOOGLEMEET",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="google_meet_agent",
            tool_space="googlemeet",
            handoff_tool_name="call_google_meet_agent",
            domain="video conferencing and meeting management",
            capabilities="scheduling meetings, managing video conferences, creating meeting links, and organizing virtual collaboration",
            use_cases="scheduling video meetings, managing Google Meet conferences, or virtual collaboration tasks",
            system_prompt=GOOGLE_MEET_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="google_maps",
        name="Google Maps",
        description="Search locations, get directions, and manage place information",
        category="productivity",
        provider="google_maps",
        scopes=[],
        available=True,
        short_name="maps",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_vy6NqsFlzLuO",
            toolkit="GOOGLE_MAPS",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="google_maps_agent",
            tool_space="google_maps",
            handoff_tool_name="call_google_maps_agent",
            domain="location and navigation services",
            capabilities="searching locations, getting directions, finding places, analyzing geographic data, and managing location information",
            use_cases="location search, getting directions, finding nearby places, or any Google Maps operation",
            system_prompt=GOOGLE_MAPS_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="asana",
        name="Asana",
        description="Manage projects, tasks, and team workflows with comprehensive project management",
        category="business",
        provider="asana",
        scopes=[],
        available=True,
        short_name="asana",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_gF2RuhulKw3I",
            toolkit="ASANA",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="asana_agent",
            tool_space="asana",
            handoff_tool_name="call_asana_agent",
            domain="project and task management",
            capabilities="creating tasks, managing projects, organizing workflows, assigning work, tracking progress, and building team collaboration systems",
            use_cases="project management, task organization, team collaboration, or any Asana workflow operation",
            system_prompt=ASANA_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="trello",
        name="Trello",
        description="Organize projects with boards, lists, and cards for visual task management",
        category="productivity",
        provider="trello",
        scopes=[],
        available=True,
        short_name="trello",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_nMjBqOcjLTGW",
            toolkit="TRELLO",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="trello_agent",
            tool_space="trello",
            handoff_tool_name="call_trello_agent",
            domain="visual project management",
            capabilities="creating boards, managing cards, organizing lists, tracking workflows, assigning tasks, and building visual project systems",
            use_cases="board management, card organization, visual task tracking, or any Trello operation",
            system_prompt=TRELLO_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="instagram",
        name="Instagram",
        description="Manage your Instagram account, post content, and engage with your audience",
        category="social_media",
        provider="instagram",
        scopes=[],
        available=True,
        short_name="instagram",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_JP45uYkUcjVV",
            toolkit="INSTAGRAM",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="instagram_agent",
            tool_space="instagram",
            handoff_tool_name="call_instagram_agent",
            domain="social media content and engagement",
            capabilities="posting content, managing stories, engaging with followers, analyzing insights, and building social media presence",
            use_cases="posting to Instagram, managing content, engaging with audience, or social media management tasks",
            system_prompt=INSTAGRAM_AGENT_SYSTEM_PROMPT,
        ),
    ),
    OAuthIntegration(
        id="clickup",
        name="ClickUp",
        description="Manage tasks, projects, and workflows with comprehensive project management",
        category="productivity",
        provider="clickup",
        scopes=[],
        available=True,
        short_name="clickup",
        managed_by="composio",
        composio_config=ComposioConfig(
            auth_config_id="ac_cyT9vqo3pcF3",
            toolkit="CLICKUP",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="clickup_agent",
            tool_space="clickup",
            handoff_tool_name="call_clickup_agent",
            domain="comprehensive project management",
            capabilities="managing tasks, organizing projects, tracking time, building workflows, assigning work, and comprehensive productivity management",
            use_cases="task management, project organization, time tracking, or any ClickUp operation",
            system_prompt=CLICKUP_AGENT_SYSTEM_PROMPT,
        ),
    ),
    # MCP Integrations (no authentication required)
    OAuthIntegration(
        id="deepwiki",
        name="DeepWiki",
        description="AI-powered documentation for any GitHub repository. Ask questions and explore codebases.",
        category="developer",
        provider="deepwiki",
        scopes=[],
        available=True,
        short_name="deepwiki",
        managed_by="mcp",
        mcp_config=MCPConfig(
            server_url="https://mcp.deepwiki.com/sse",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="deepwiki_agent",
            tool_space="deepwiki",
            handoff_tool_name="call_deepwiki_agent",
            domain="GitHub repository documentation and code understanding",
            capabilities="reading wiki structure, viewing documentation contents, asking questions about any GitHub repository",
            use_cases="exploring codebases, understanding repositories, asking questions about GitHub projects",
            system_prompt=DEEPWIKI_AGENT_SYSTEM_PROMPT,
            use_direct_tools=True,
            disable_retrieve_tools=True,
        ),
    ),
    # HackerNews MCP (unauthenticated, Composio hosted)
    OAuthIntegration(
        id="hackernews",
        name="Hacker News",
        description="Browse and search Hacker News stories, comments, and discussions.",
        category="news",
        provider="hackernews",
        scopes=[],
        available=True,
        short_name="hn",
        managed_by="mcp",
        mcp_config=MCPConfig(
            server_url="https://backend.composio.dev/v3/mcp/0f5b8d43-4e16-4919-8788-b462f1089b91/mcp",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="hackernews_agent",
            tool_space="hackernews",
            handoff_tool_name="call_hackernews_agent",
            domain="tech news and discussions",
            capabilities="browsing Hacker News, searching stories, reading comments and discussions",
            use_cases="checking top stories, searching for tech news, reading discussions",
            system_prompt="You are a Hacker News assistant. Help users browse and search tech news, stories, and discussions.",
            use_direct_tools=True,
        ),
    ),
    # Instacart MCP (unauthenticated, Composio hosted)
    OAuthIntegration(
        id="instacart",
        name="Instacart",
        description="Search and browse grocery products, recipes, and shopping options.",
        category="lifestyle",
        provider="instacart",
        scopes=[],
        available=True,
        short_name="instacart",
        managed_by="mcp",
        mcp_config=MCPConfig(
            server_url="https://backend.composio.dev/v3/mcp/6bb2556a-57ef-4daa-81ad-bd1e3f9e443d/mcp?user_id=pg-test-15a6d21a-2a4b-4be5-98c9-d92f55b3ccc3",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="instacart_agent",
            tool_space="instacart",
            handoff_tool_name="call_instacart_agent",
            domain="grocery shopping and recipes",
            capabilities="searching grocery products, finding recipes, browsing shopping options",
            use_cases="finding groceries, searching recipes, planning meals",
            system_prompt="You are an Instacart assistant. Help users search for groceries, find recipes, and plan their shopping.",
            use_direct_tools=True,
        ),
    ),
    # Yelp MCP (unauthenticated, Composio hosted)
    OAuthIntegration(
        id="yelp",
        name="Yelp",
        description="Search for local businesses, restaurants, and read reviews.",
        category="lifestyle",
        provider="yelp",
        scopes=[],
        available=True,
        short_name="yelp",
        managed_by="mcp",
        mcp_config=MCPConfig(
            server_url="https://backend.composio.dev/v3/mcp/8e1efded-6b08-4346-a657-92d0b94399e5/mcp?user_id=pg-test-15a6d21a-2a4b-4be5-98c9-d92f55b3ccc3",
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="yelp_agent",
            tool_space="yelp",
            handoff_tool_name="call_yelp_agent",
            domain="local business search and reviews",
            capabilities="searching local businesses, finding restaurants, reading reviews, getting business information",
            use_cases="finding restaurants, searching local services, reading reviews",
            system_prompt="You are a Yelp assistant. Help users find local businesses, restaurants, and services with reviews and ratings.",
            use_direct_tools=True,
        ),
    ),
    # Context7 MCP (Smithery-hosted, OAuth via MCP spec discovery)
    OAuthIntegration(
        id="context7",
        name="Context7",
        description="Fetch up-to-date, version-specific documentation and code examples for any library or framework.",
        category="developer",
        provider="context7",
        scopes=[],
        available=True,
        is_featured=False,
        short_name="context7",
        managed_by="mcp",
        mcp_config=MCPConfig(
            server_url="https://server.smithery.ai/@upstash/context7-mcp",
            requires_auth=True,
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="context7_agent",
            tool_space="context7",
            handoff_tool_name="call_context7_agent",
            domain="library documentation and code examples",
            capabilities="resolving library identifiers, fetching up-to-date documentation, providing version-specific code examples, eliminating hallucinated APIs",
            use_cases="getting accurate documentation, finding code examples, checking API references, learning about libraries",
            system_prompt=CONTEXT7_AGENT_SYSTEM_PROMPT,
        ),
    ),
    # Perplexity MCP (Smithery-hosted, OAuth via MCP spec discovery)
    OAuthIntegration(
        id="perplexity",
        name="Perplexity",
        description="AI-powered web search with detailed, contextually relevant results and citations.",
        category="productivity",
        provider="perplexity",
        scopes=[],
        available=True,
        is_featured=True,
        short_name="perplexity",
        managed_by="mcp",
        mcp_config=MCPConfig(
            server_url="https://server.smithery.ai/@arjunkmrm/perplexity-search",
            requires_auth=True,
        ),
        subagent_config=SubAgentConfig(
            has_subagent=True,
            agent_name="perplexity_agent",
            tool_space="perplexity",
            handoff_tool_name="call_perplexity_agent",
            domain="AI-powered web search",
            capabilities="performing comprehensive web searches, providing contextually relevant results with citations, filtering by recency",
            use_cases="web searches, research, finding current information, fact-checking, getting cited answers",
            system_prompt=PERPLEXITY_AGENT_SYSTEM_PROMPT,
            use_direct_tools=True,
        ),
    ),
]


@cache
def get_integration_by_id(integration_id: str) -> Optional[OAuthIntegration]:
    """Get an integration by its ID."""
    return next((i for i in OAUTH_INTEGRATIONS if i.id == integration_id), None)


@cache
def get_integration_scopes(integration_id: str) -> List[str]:
    """Get the OAuth scopes for a specific integration."""
    integration = get_integration_by_id(integration_id)
    if not integration:
        return []
    return [scope.scope for scope in integration.scopes]


@cache
def get_short_name_mapping() -> Dict[str, str]:
    """Get mapping of short names to integration IDs."""
    return {i.short_name: i.id for i in OAUTH_INTEGRATIONS if i.short_name}


@cache
def get_composio_social_configs() -> Dict[str, ComposioConfig]:
    """Get COMPOSIO_SOCIAL_CONFIGS from integrations managed by Composio."""
    configs = {}
    for integration in OAUTH_INTEGRATIONS:
        if integration.managed_by == "composio" and integration.composio_config:
            configs[integration.provider] = integration.composio_config
    return configs


@cache
def get_integration_by_config(auth_config_id: str) -> Optional[OAuthIntegration]:
    """Get an integration by its Composio auth config ID."""
    return next(
        (
            i
            for i in OAUTH_INTEGRATIONS
            if i.composio_config and i.composio_config.auth_config_id == auth_config_id
        ),
        None,
    )
