/**
 * Build script to extract SVG path data from gaia-icons React components
 * 
 * Run with: npx tsx apps/web/scripts/extract-icon-paths.ts
 * 
 * This generates a JSON file with pre-extracted SVG paths that can be used
 * in Edge runtime (like OG image generation) where React components can't
 * be rendered.
 */

import * as React from "react";
import * as ReactDOMServer from "react-dom/server";
import * as fs from "fs";
import * as path from "path";

// Import icons that are used for category rendering
import {
  AlarmClockIcon,
  Brain02Icon,
  CheckListIcon,
  ComputerTerminal01Icon,
  ConnectIcon,
  FileEmpty02Icon,
  Image02Icon,
  InformationCircleIcon,
  NotificationIcon,
  PackageOpenIcon,
  SourceCodeCircleIcon,
  SquareArrowUpRight02Icon,
  Target02Icon,
  ToolsIcon,
} from "@theexperiencecompany/gaia-icons/solid-rounded";

type IconComponent = React.ComponentType<{
  size?: number;
  color?: string;
  strokeWidth?: number;
}>;

interface ExtractedSvgData {
  viewBox: string;
  paths: string[];
}

/**
 * Extract SVG path data from a gaia-icons component
 */
function extractSvgPaths(IconComponent: IconComponent): ExtractedSvgData {
  // Render the icon to static HTML
  const html = ReactDOMServer.renderToStaticMarkup(
    React.createElement(IconComponent, {
      size: 24,
      color: "currentColor",
      strokeWidth: 1.5,
    })
  );

  // Extract viewBox
  const viewBoxMatch = html.match(/viewBox="([^"]+)"/);
  const viewBox = viewBoxMatch?.[1] || "0 0 24 24";

  // Extract all path d attributes
  const pathRegex = /<path[^>]*d="([^"]+)"[^>]*>/g;
  const paths: string[] = [];
  let match;
  while ((match = pathRegex.exec(html)) !== null) {
    if (match[1]) {
      paths.push(match[1]);
    }
  }

  return { viewBox, paths };
}

// Map of icon names to their components
const icons: Record<string, IconComponent> = {
  CheckListIcon,
  AlarmClockIcon,
  FileEmpty02Icon,
  SourceCodeCircleIcon,
  Brain02Icon,
  Image02Icon,
  Target02Icon,
  NotificationIcon,
  InformationCircleIcon,
  ToolsIcon,
  ConnectIcon,
  SquareArrowUpRight02Icon,
  PackageOpenIcon,
  ComputerTerminal01Icon,
};

// Extract paths from all icons
const iconPaths: Record<string, ExtractedSvgData> = {};

for (const [name, component] of Object.entries(icons)) {
  console.log(`Extracting paths from ${name}...`);
  iconPaths[name] = extractSvgPaths(component);
  console.log(`  Found ${iconPaths[name].paths.length} paths`);
}

// ESM-compatible directory resolution
import { fileURLToPath } from 'url';
import { dirname } from 'path';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Write to JSON file
const outputPath = path.join(
  __dirname,
  "../src/config/iconPaths.generated.json"
);
fs.writeFileSync(outputPath, JSON.stringify(iconPaths, null, 2));
console.log(`\nWrote icon paths to ${outputPath}`);

// Also output TypeScript file for type safety
const tsContent = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by: npx tsx apps/web/scripts/extract-icon-paths.ts
 */

export interface ExtractedSvgData {
  readonly viewBox: string;
  readonly paths: readonly string[];
}

export const iconPaths: Record<string, ExtractedSvgData> = ${JSON.stringify(iconPaths, null, 2)};

export function getIconPaths(iconName: string): ExtractedSvgData | null {
  return iconPaths[iconName] || null;
}
`;

const tsOutputPath = path.join(
  __dirname,
  "../src/config/iconPaths.generated.ts"
);
fs.writeFileSync(tsOutputPath, tsContent);
console.log(`Wrote TypeScript file to ${tsOutputPath}`);
