"""Platform Models

Pydantic models for platform account linking and authentication.
"""

from typing import TypedDict

from pydantic import BaseModel, Field


class LinkPlatformRequest(BaseModel):
    """Request model for linking a platform account via secure token."""

    token: str = Field(..., description="Secure link token generated by the bot")


class PlatformLinkEntry(BaseModel):
    """A single linked platform entry returned in the platform links response."""

    platform: str = Field(..., description="Platform name")
    platformUserId: str = Field(..., description="User's plain string ID on the platform")
    username: str | None = Field(None, description="Username on the platform")
    displayName: str | None = Field(None, description="Display name on the platform")
    connectedAt: str | None = Field(None, description="ISO timestamp when linked")


class PlatformLinkView(TypedDict):
    """One entry of ``PlatformLinkService.get_linked_platforms``'s mapping.

    A ``TypedDict`` mirroring :class:`PlatformLinkEntry`, not that model (Type
    Safety item 6): the value is assembled in-process from an already-loaded
    ``UserDocument`` and is consumed by the outbound-delivery paths, which
    tolerate a legacy non-string ``platformUserId`` (Telegram stores chat_id as
    an int) and coerce it themselves at the envelope. Validating here instead
    would start raising on those rows — a behaviour change (item 13). The HTTP
    boundary still validates, via ``GetPlatformLinksResponse`` below.
    """

    platform: str
    platformUserId: str
    username: str | None
    displayName: str | None
    connectedAt: str | None


class GetPlatformLinksResponse(BaseModel):
    """Response wrapper for user's linked platforms."""

    platform_links: dict[str, PlatformLinkEntry] = Field(
        default_factory=dict,
        description="Map of platform name to link details",
    )


class PlatformLinkResult(BaseModel):
    """What ``PlatformLinkService.link_account`` reports back to its callers.

    Mirrors :class:`LinkPlatformResponse` plus ``is_new_link``, which is
    deliberately internal: it tells a caller whether to fire the one-off
    "connected" greeting and is not part of the HTTP payload.
    """

    status: str
    platform: str
    platform_user_id: str
    connected_at: str
    is_new_link: bool


class LinkPlatformResponse(BaseModel):
    """Response model for linking a platform account."""

    status: str = Field(..., description="Link status (e.g., 'linked')")
    platform: str = Field(..., description="Platform name")
    platform_user_id: str | None = Field(None, description="Platform user ID")
    connected_at: str | None = Field(None, description="Connection timestamp")


class DisconnectPlatformResponse(BaseModel):
    """Response model for disconnecting a platform account."""

    status: str = Field(..., description="Disconnect status (e.g., 'disconnected')")
    platform: str = Field(..., description="Platform name")


class InitiatePlatformConnectResponse(BaseModel):
    """Response model for initiating platform connection."""

    auth_url: str | None = Field(None, description="OAuth authorization URL (if OAuth configured)")
    auth_type: str = Field(..., description="Authentication type ('oauth' or 'manual')")
    instructions: str | None = Field(
        None, description="Manual linking instructions (if manual auth)"
    )
    action_link: str | None = Field(
        None, description="Optional deep-link for manual auth (e.g. Telegram bot URL)"
    )
