"""Platform Models

Pydantic models for platform account linking and authentication.
"""

from typing import Optional

from pydantic import BaseModel, Field


class LinkPlatformRequest(BaseModel):
    """Request model for linking a platform account via secure token."""

    token: str = Field(..., description="Secure link token generated by the bot")


class PlatformAuthStatusResponse(BaseModel):
    """Response model for platform authentication status check."""

    authenticated: bool = Field(..., description="Whether user is linked")
    platform: str = Field(..., description="Platform name")
    platform_user_id: str = Field(..., description="User's platform ID")


class PlatformLinkEntry(BaseModel):
    """A single linked platform entry returned in the platform links response."""

    platform: str = Field(..., description="Platform name")
    platformUserId: str = Field(
        ..., description="User's plain string ID on the platform"
    )
    username: Optional[str] = Field(None, description="Username on the platform")
    displayName: Optional[str] = Field(None, description="Display name on the platform")
    connectedAt: Optional[str] = Field(None, description="ISO timestamp when linked")


class GetPlatformLinksResponse(BaseModel):
    """Response wrapper for user's linked platforms."""

    platform_links: dict[str, PlatformLinkEntry] = Field(
        default_factory=dict,
        description="Map of platform name to link details",
    )


class LinkPlatformResponse(BaseModel):
    """Response model for linking a platform account."""

    status: str = Field(..., description="Link status (e.g., 'linked')")
    platform: str = Field(..., description="Platform name")
    platform_user_id: Optional[str] = Field(None, description="Platform user ID")
    connected_at: Optional[str] = Field(None, description="Connection timestamp")


class DisconnectPlatformResponse(BaseModel):
    """Response model for disconnecting a platform account."""

    status: str = Field(..., description="Disconnect status (e.g., 'disconnected')")
    platform: str = Field(..., description="Platform name")


class InitiatePlatformConnectResponse(BaseModel):
    """Response model for initiating platform connection."""

    auth_url: Optional[str] = Field(
        None, description="OAuth authorization URL (if OAuth configured)"
    )
    auth_type: str = Field(..., description="Authentication type ('oauth' or 'manual')")
    instructions: Optional[str] = Field(
        None, description="Manual linking instructions (if manual auth)"
    )
    action_link: Optional[str] = Field(
        None, description="Optional deep-link for manual auth (e.g. Telegram bot URL)"
    )
