"""Platform Models

Pydantic models for platform account linking and authentication.
"""

from typing import Annotated, TypedDict

from pydantic import BaseModel, Field


class LinkPlatformRequest(BaseModel):
    """Request model for linking a platform account via secure token."""

    token: str = Field(..., description="Secure link token generated by the bot")


class PlatformLinkEntry(TypedDict):
    """One linked platform account — the single shape for this entry.

    A ``TypedDict`` rather than a model (Type Safety item 6) because it has two
    consumers with different needs, and this type serves both without a rival
    copy. ``PlatformLinkService.get_linked_platforms`` assembles it in-process
    from an already-loaded ``UserDocument``, and the outbound-delivery paths
    read it tolerating a legacy non-string ``platformUserId`` (Telegram stores
    chat_id as an int) which they coerce at the envelope; validating there would
    start raising on those rows — a behaviour change (item 13). Pydantic still
    validates it as a field of ``GetPlatformLinksResponse`` below, so the HTTP
    boundary rejects the same values a ``BaseModel`` here would.
    """

    platform: Annotated[str, Field(description="Platform name")]
    platformUserId: Annotated[str, Field(description="User's plain string ID on the platform")]
    username: Annotated[str | None, Field(description="Username on the platform")]
    displayName: Annotated[str | None, Field(description="Display name on the platform")]
    connectedAt: Annotated[str | None, Field(description="ISO timestamp when linked")]


class GetPlatformLinksResponse(BaseModel):
    """Response wrapper for user's linked platforms."""

    platform_links: dict[str, PlatformLinkEntry] = Field(
        default_factory=dict,
        description="Map of platform name to link details",
    )


class PlatformLinkResult(BaseModel):
    """What ``PlatformLinkService.link_account`` reports back to its callers.

    Mirrors :class:`LinkPlatformResponse` plus ``is_new_link``, which is
    deliberately internal: it tells a caller whether to fire the one-off
    "connected" greeting and is not part of the HTTP payload.
    """

    status: str
    platform: str
    platform_user_id: str
    connected_at: str
    is_new_link: bool


class LinkPlatformResponse(BaseModel):
    """Response model for linking a platform account."""

    status: str = Field(..., description="Link status (e.g., 'linked')")
    platform: str = Field(..., description="Platform name")
    platform_user_id: str | None = Field(None, description="Platform user ID")
    connected_at: str | None = Field(None, description="Connection timestamp")


class DisconnectPlatformResponse(BaseModel):
    """Response model for disconnecting a platform account."""

    status: str = Field(..., description="Disconnect status (e.g., 'disconnected')")
    platform: str = Field(..., description="Platform name")


class InitiatePlatformConnectResponse(BaseModel):
    """Response model for initiating platform connection."""

    auth_url: str | None = Field(None, description="OAuth authorization URL (if OAuth configured)")
    auth_type: str = Field(..., description="Authentication type ('oauth' or 'manual')")
    instructions: str | None = Field(
        None, description="Manual linking instructions (if manual auth)"
    )
    action_link: str | None = Field(
        None, description="Optional deep-link for manual auth (e.g. Telegram bot URL)"
    )
