"""
Cache Constants.

Centralized cache-related constants including TTL values and key prefixes.
Import these instead of defining local constants in services.
"""

# TTL values (in seconds)
ONE_YEAR_TTL = 31_536_000
SIX_MONTH_TTL = 15_552_000
ONE_DAY_TTL = 86_400
SIX_HOUR_TTL = 21_600
ONE_HOUR_TTL = 3_600
THIRTY_MINUTES_TTL = 1_800
TEN_MINUTES_TTL = 600
FIVE_MINUTES_TTL = 300


# TTL Aliases
DEFAULT_CACHE_TTL = ONE_HOUR_TTL
STATS_CACHE_TTL = THIRTY_MINUTES_TTL
CUSTOM_INT_METADATA_TTL = ONE_HOUR_TTL
SUBAGENT_CACHE_TTL = ONE_HOUR_TTL
OAUTH_STATE_TTL = TEN_MINUTES_TTL
OAUTH_DISCOVERY_TTL = ONE_DAY_TTL
MCP_TOOLS_CACHE_TTL = ONE_DAY_TTL
GLOBAL_TOOLS_CACHE_TTL = SIX_HOUR_TTL
COMMUNITY_CACHE_TTL = FIVE_MINUTES_TTL
FAVICON_CACHE_TTL = SIX_MONTH_TTL
SEARCH_CACHE_TTL = ONE_DAY_TTL
STREAM_TTL = FIVE_MINUTES_TTL
STATE_TOKEN_TTL = TEN_MINUTES_TTL
MOBILE_REDIRECT_TTL = FIVE_MINUTES_TTL

# Cache key prefixes
TEAM_CACHE_PREFIX = "team"
CUSTOM_INT_METADATA_CACHE_PREFIX = "custom_int_metadata"
HANDOFF_METADATA_CACHE_PREFIX = "handoff_metadata"
SUBAGENT_CACHE_PREFIX = "subagent_info"
OAUTH_STATE_PREFIX = "mcp_oauth_state"
OAUTH_DISCOVERY_PREFIX = "mcp_oauth_discovery"
OAUTH_STATUS_KEY = "OAUTH_STATUS"
MCP_TOOLS_CACHE_KEY = "mcp:tools:all"
GLOBAL_TOOLS_CACHE_KEY = "tools:global"
STREAM_CHANNEL_PREFIX = "stream:channel:"
STREAM_SIGNAL_PREFIX = "stream:signal:"
STREAM_PROGRESS_PREFIX = "stream:progress:"
STATE_KEY_PREFIX = "oauth_state"
