"""
General Constants.

Centralized general-purpose constants.
"""

NEW_MESSAGE_BREAKER = "<NEW_MESSAGE_BREAK>"

DEDUPLICATION_SIMILARITY_THRESHOLD = 0.9
PROFILE_EXTRACTION_LLM_PROVIDER = "gemini"
PROFILE_EXTRACTION_LLM_MODEL = "gemini-2.0-flash"
