"""Curated HIL destructive-tool sets per integration.

A tool is listed here only when its action is IRREVERSIBLE — it cannot be undone
by any later tool call or UI action. Three buckets qualify:
  1. Outbound communication that reaches people (send email/DM/message, public post).
  2. Permanent deletion that bypasses trash/recycle.
  3. Financial actions (pay / purchase / checkout).
Reversible actions — trash/archive, create/update/edit, follow/like/star/react,
labels, internal comments, reads — are NOT listed. Each integration references its
constant via ``destructive_tools=`` in ``app/config/oauth_config.py``; the registry
stamps ``Tool.destructive`` from it. A present (possibly empty) list = reviewed:
exactly those gate, every other tool in the toolkit is safe. These are the DEFAULT
gated set; users override per tool via HIL ``tool_overrides``.
"""

GOOGLECALENDAR_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLECALENDAR_CALENDARS_DELETE",
    "GOOGLECALENDAR_CALENDAR_LIST_DELETE",
    "GOOGLECALENDAR_CLEAR_CALENDAR",
    "GOOGLECALENDAR_DELETE_EVENT",
]

GOOGLEDOCS_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLEDOCS_DELETE_TAB",
]

# Only permanent, trash-bypassing deletes gate. TRASH_FILE / UNTRASH_FILE are
# reversible (recoverable from Drive trash) and are NOT listed; permission
# changes are reversible too. DELETE_REVISION permanently drops a file version.
GOOGLEDRIVE_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLEDRIVE_DELETE_DRIVE",
    "GOOGLEDRIVE_DELETE_FILE",
    "GOOGLEDRIVE_DELETE_REVISION",
    "GOOGLEDRIVE_DELETE_TEAM_DRIVE",
    "GOOGLEDRIVE_EMPTY_TRASH",
    "GOOGLEDRIVE_GOOGLE_DRIVE_DELETE_FOLDER_OR_FILE_ACTION",
]

# GMAIL_DELETE_DRAFT is intentionally NOT gated: a draft is an unsent, agent-managed
# artifact, and revising a draft means deleting the old one and creating a new one
# (Gmail has no in-place edit). Gating it would prompt on every draft edit — routine
# cleanup, not irreversible loss of real mail. Real message deletes below stay gated.
GMAIL_DESTRUCTIVE_TOOLS: list[str] = [
    "GMAIL_BATCH_DELETE_MESSAGES",
    "GMAIL_DELETE_FILTER",
    "GMAIL_DELETE_LABEL",
    "GMAIL_DELETE_MESSAGE",
    "GMAIL_DELETE_THREAD",
    "GMAIL_FORWARD_MESSAGE",
    "GMAIL_REMOVE_LABEL",
    "GMAIL_REPLY_TO_THREAD",
    "GMAIL_SEND_DRAFT",
    "GMAIL_SEND_EMAIL",
]

NOTION_DESTRUCTIVE_TOOLS: list[str] = []

TWITTER_DESTRUCTIVE_TOOLS: list[str] = [
    "TWITTER_CREATE_DM_CONVERSATION",
    "TWITTER_CREATION_OF_A_POST",
    "TWITTER_DELETE_DM",
    "TWITTER_DELETE_LIST",
    "TWITTER_POST_DELETE_BY_POST_ID",
    "TWITTER_SEND_A_NEW_MESSAGE_TO_A_USER",
    "TWITTER_SEND_DM_TO_CONVERSATION",
]

GOOGLESHEETS_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLESHEETS_DELETE_CHART",
]

LINKEDIN_DESTRUCTIVE_TOOLS: list[str] = [
    "LINKEDIN_CREATE_ARTICLE_OR_URL_SHARE",
    "LINKEDIN_CREATE_COMMENT_ON_POST",
    "LINKEDIN_CREATE_LINKED_IN_POST",
    "LINKEDIN_DELETE_LINKED_IN_POST",
    "LINKEDIN_DELETE_POST",
    "LINKEDIN_DELETE_UGC_POST",
]

GITHUB_DESTRUCTIVE_TOOLS: list[str] = [
    "GITHUB_DELETE_AN_ISSUE_COMMENT",
    "GITHUB_DELETE_A_FILE",
    "GITHUB_DELETE_A_LABEL",
    "GITHUB_MERGE_A_BRANCH",
    "GITHUB_MERGE_A_PULL_REQUEST",
]

REDDIT_DESTRUCTIVE_TOOLS: list[str] = [
    "REDDIT_CREATE_REDDIT_POST",
    "REDDIT_DELETE_REDDIT_COMMENT",
    "REDDIT_DELETE_REDDIT_POST",
    "REDDIT_POST_REDDIT_COMMENT",
]

AIRTABLE_DESTRUCTIVE_TOOLS: list[str] = [
    "AIRTABLE_DELETE_COMMENT",
    "AIRTABLE_DELETE_MULTIPLE_RECORDS",
    "AIRTABLE_DELETE_RECORD",
]

LINEAR_DESTRUCTIVE_TOOLS: list[str] = [
    "LINEAR_DELETE_LINEAR_ISSUE",
    "LINEAR_RUN_QUERY_OR_MUTATION",
]

SLACK_DESTRUCTIVE_TOOLS: list[str] = [
    "SLACK_DELETES_A_MESSAGE_FROM_A_CHAT",
    "SLACK_DELETE_A_FILE_BY_ID",
    "SLACK_DELETE_CANVAS",
    "SLACK_SCHEDULE_MESSAGE",
    "SLACK_SEND_EPHEMERAL_MESSAGE",
    "SLACK_SEND_MESSAGE",
]

HUBSPOT_DESTRUCTIVE_TOOLS: list[str] = [
    "HUBSPOT_DELETE_CALL",
    "HUBSPOT_DELETE_CALLING_EXTENSION_SETTINGS",
    "HUBSPOT_DELETE_CAMPAIGN",
    "HUBSPOT_DELETE_COMPANY_GDPR",
    "HUBSPOT_DELETE_CONTACT_GDPR",
    "HUBSPOT_DELETE_LINE_ITEMS_GDPR",
    "HUBSPOT_DELETE_MARKETING_EMAIL",
    "HUBSPOT_DELETE_PIPELINE",
    "HUBSPOT_DELETE_PIPELINE_STAGE",
    "HUBSPOT_DELETE_SCHEMA",
    "HUBSPOT_DELETE_TIMELINE_EVENT_TEMPLATE",
    "HUBSPOT_DELETE_VIDEO_CONFERENCING_APP_SETTINGS",
    "HUBSPOT_DELETE_WORKFLOW",
    "HUBSPOT_PERMANENTLY_DELETE_CONTACT_VIA_GDPR",
    "HUBSPOT_PUBLISH_MARKETING_EMAIL",
    "HUBSPOT_PURGE_SCHEMA",
]

GOOGLETASKS_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLETASKS_BATCH_EXECUTE",
    "GOOGLETASKS_CLEAR_TASKS",
    "GOOGLETASKS_DELETE_TASK",
    "GOOGLETASKS_DELETE_TASK_LIST",
]

TODOIST_DESTRUCTIVE_TOOLS: list[str] = [
    "TODOIST_DELETE_COMMENT",
    "TODOIST_DELETE_LABEL_V1",
    "TODOIST_DELETE_PROJECT2",
    "TODOIST_DELETE_SECTION2",
    "TODOIST_DELETE_TASK",
    "TODOIST_DELETE_TASK_V1",
    "TODOIST_DELETE_UPLOAD",
    "TODOIST_REMOVE_SHARED_LABEL_V1",
    "TODOIST_SYNC",
]

MICROSOFT_TEAMS_DESTRUCTIVE_TOOLS: list[str] = [
    "MICROSOFT_TEAMS_DELETE_CHANNEL",
    "MICROSOFT_TEAMS_DELETE_TEAM",
    "MICROSOFT_TEAMS_POST_MESSAGE_REPLY",
    "MICROSOFT_TEAMS_SEND_ACTIVITY_NOTIFICATION",
    "MICROSOFT_TEAMS_TEAMS_POST_CHANNEL_MESSAGE",
    "MICROSOFT_TEAMS_TEAMS_POST_CHAT_MESSAGE",
    "MICROSOFT_TEAMS_TEAMS_POST_MESSAGE_REPLY",
]

ZOOM_DESTRUCTIVE_TOOLS: list[str] = [
    "ZOOM_CHAT",
    "ZOOM_DELETE_A_MEETING",
    "ZOOM_DELETE_IQ_CONVERSATION",
    "ZOOM_DELETE_IQ_CONVERSATION_COMMENT",
    "ZOOM_DELETE_IQ_DEAL_ACTIVITIES",
    "ZOOM_DELETE_MEETING_RECORDINGS",
    "ZOOM_DELETE_PROJECT",
    "ZOOM_DELETE_RECORDING_FILE",
    "ZOOM_DELETE_WHITEBOARD",
    "ZOOM_DELETE_ZRA_CONVERSATION",
    "ZOOM_DELETE_ZRA_CONVERSATION_COMMENT",
    "ZOOM_DELETE_ZRA_CRM_SETTINGS",
    "ZOOM_DELETE_ZRA_DEAL_ACTIVITIES",
]

GOOGLEMEET_DESTRUCTIVE_TOOLS: list[str] = []

GOOGLE_MAPS_DESTRUCTIVE_TOOLS: list[str] = []

ASANA_DESTRUCTIVE_TOOLS: list[str] = [
    "ASANA_DELETE_ALLOCATION",
    "ASANA_DELETE_ATTACHMENT",
    "ASANA_DELETE_CUSTOM_FIELD",
    "ASANA_DELETE_MEMBERSHIP",
    "ASANA_DELETE_PROJECT",
    "ASANA_DELETE_PROJECT_BRIEF",
    "ASANA_DELETE_PROJECT_STATUS",
    "ASANA_DELETE_SECTION",
    "ASANA_DELETE_STATUS_UPDATE",
    "ASANA_DELETE_STORY",
    "ASANA_DELETE_TAG",
    "ASANA_DELETE_TASK",
    "ASANA_SUBMIT_PARALLEL_REQUESTS",
]

TRELLO_DESTRUCTIVE_TOOLS: list[str] = [
    "TRELLO_DELETE_ACTION",
    "TRELLO_DELETE_BOARD",
    "TRELLO_DELETE_CARDS_BY_ID_CARD",
    "TRELLO_DELETE_CARD_ATTACHMENT",
    "TRELLO_DELETE_CARD_CHECKLIST",
    "TRELLO_DELETE_CARD_COMMENT",
    "TRELLO_DELETE_CHECKLISTS_BY_ID_CHECKLIST",
    "TRELLO_DELETE_CHECKLIST_ITEM",
    "TRELLO_DELETE_LABELS_BY_ID_LABEL",
    "TRELLO_DELETE_MEMBER_BOARD_BACKGROUND",
    "TRELLO_DELETE_MEMBER_CUSTOM_STICKER",
    "TRELLO_DELETE_MEMBER_SAVED_SEARCH",
    "TRELLO_DELETE_ORGANIZATIONS_BY_ID_ORG",
    "TRELLO_DELETE_TOKENS_BY_TOKEN",
    "TRELLO_DELETE_TOKENS_WEBHOOKS_BY_TOKEN_BY_ID_WEBHOOK",
    "TRELLO_DELETE_WEBHOOKS_BY_ID_WEBHOOK",
]

INSTAGRAM_DESTRUCTIVE_TOOLS: list[str] = [
    "INSTAGRAM_CREATE_POST",
    "INSTAGRAM_DELETE_COMMENT",
    "INSTAGRAM_DELETE_MESSENGER_PROFILE",
    "INSTAGRAM_POST_IG_COMMENT_REPLIES",
    "INSTAGRAM_POST_IG_MEDIA_COMMENTS",
    "INSTAGRAM_POST_IG_USER_MEDIA_PUBLISH",
    "INSTAGRAM_POST_IG_USER_MENTIONS",
    "INSTAGRAM_REPLY_TO_COMMENT",
    "INSTAGRAM_SEND_IMAGE",
    "INSTAGRAM_SEND_TEXT_MESSAGE",
]

CLICKUP_DESTRUCTIVE_TOOLS: list[str] = [
    "CLICKUP_CREATE_CHAT_MESSAGE",
    "CLICKUP_CREATE_DIRECT_MESSAGE_CHANNEL",
    "CLICKUP_CREATE_REPLY_MESSAGE",
    "CLICKUP_DELETE_CHAT_CHANNEL",
    "CLICKUP_DELETE_CHAT_MESSAGE",
    "CLICKUP_DELETE_CHECKLIST",
    "CLICKUP_DELETE_CHECKLIST_ITEM",
    "CLICKUP_DELETE_COMMENT",
    "CLICKUP_DELETE_FOLDER",
    "CLICKUP_DELETE_GOAL",
    "CLICKUP_DELETE_KEY_RESULT",
    "CLICKUP_DELETE_LIST",
    "CLICKUP_DELETE_SPACE",
    "CLICKUP_DELETE_TASK",
    "CLICKUP_DELETE_TEAM",
    "CLICKUP_DELETE_TIME_ENTRY",
    "CLICKUP_DELETE_TIME_TRACKED",
    "CLICKUP_DELETE_VIEW",
    "CLICKUP_DELETE_WEBHOOK",
]
