"""Curated HIL destructive-tool sets per integration.

A tool is listed here only when its action is IRREVERSIBLE — it cannot be undone
by any later tool call or UI action. Three buckets qualify:
  1. Outbound communication that reaches people (send email/DM/message, public post).
  2. Permanent deletion that bypasses trash/recycle.
  3. Financial actions (pay / purchase / checkout).
Reversible actions — trash/archive, create/update/edit, follow/like/star/react,
labels, internal comments, reads — are NOT listed. Each integration references its
constant via destructive_tools= in app/config/oauth_config.py; the registry
stamps Tool.destructive from it. A present (possibly empty) list = reviewed:
exactly those gate, every other tool in the toolkit is safe. These are the DEFAULT
gated set; users override per tool via HIL tool_overrides.
"""

GOOGLECALENDAR_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLECALENDAR_CALENDARS_DELETE",
    "GOOGLECALENDAR_CALENDAR_LIST_DELETE",
    "GOOGLECALENDAR_CLEAR_CALENDAR",
    "GOOGLECALENDAR_DELETE_EVENT",
]

GOOGLEDOCS_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLEDOCS_DELETE_TAB",
]

# Permanent, trash-bypassing deletes gate. CREATE_PERMISSION gates too: sharing
# exposes the file's contents the instant it's granted, and revoking later
# can't undo what was already read (CWE-200). TRASH_FILE stays ungated (recoverable).
GOOGLEDRIVE_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLEDRIVE_CREATE_PERMISSION",
    "GOOGLEDRIVE_DELETE_DRIVE",
    "GOOGLEDRIVE_DELETE_FILE",
    "GOOGLEDRIVE_DELETE_REVISION",
    "GOOGLEDRIVE_DELETE_TEAM_DRIVE",
    "GOOGLEDRIVE_EMPTY_TRASH",
    "GOOGLEDRIVE_GOOGLE_DRIVE_DELETE_FOLDER_OR_FILE_ACTION",
]

# GMAIL_DELETE_DRAFT is intentionally NOT gated: revising a draft deletes the
# old one and creates a new one, so gating it would prompt on routine cleanup.
GMAIL_DESTRUCTIVE_TOOLS: list[str] = [
    "GMAIL_BATCH_DELETE_MESSAGES",
    "GMAIL_DELETE_FILTER",
    "GMAIL_DELETE_LABEL",
    "GMAIL_DELETE_MESSAGE",
    "GMAIL_DELETE_THREAD",
    "GMAIL_FORWARD_MESSAGE",
    "GMAIL_REMOVE_LABEL",
    "GMAIL_REPLY_TO_THREAD",
    "GMAIL_SEND_DRAFT",
    "GMAIL_SEND_EMAIL",
]

NOTION_DESTRUCTIVE_TOOLS: list[str] = []

TWITTER_DESTRUCTIVE_TOOLS: list[str] = [
    "TWITTER_CREATE_DM_CONVERSATION",
    "TWITTER_CREATION_OF_A_POST",
    "TWITTER_DELETE_DM",
    "TWITTER_DELETE_LIST",
    "TWITTER_POST_DELETE_BY_POST_ID",
    "TWITTER_SEND_A_NEW_MESSAGE_TO_A_USER",
    "TWITTER_SEND_DM_TO_CONVERSATION",
]

GOOGLESHEETS_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLESHEETS_DELETE_CHART",
]

LINKEDIN_DESTRUCTIVE_TOOLS: list[str] = [
    "LINKEDIN_CREATE_ARTICLE_OR_URL_SHARE",
    "LINKEDIN_CREATE_COMMENT_ON_POST",
    "LINKEDIN_CREATE_LINKED_IN_POST",
    "LINKEDIN_DELETE_LINKED_IN_POST",
    "LINKEDIN_DELETE_POST",
    "LINKEDIN_DELETE_UGC_POST",
]

GITHUB_DESTRUCTIVE_TOOLS: list[str] = [
    "GITHUB_CREATE_A_PULL_REQUEST",
    "GITHUB_DISMISS_A_REVIEW_FOR_A_PULL_REQUEST",
    "GITHUB_CREATE_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER",
    "GITHUB_ADD_A_REPOSITORY_COLLABORATOR",
    "GITHUB_CREATE_OR_UPDATE_FILE_CONTENTS",
    "GITHUB_DELETE_A_FILE",
    "GITHUB_MERGE_A_BRANCH",
    "GITHUB_MERGE_A_PULL_REQUEST",
    "GITHUB_UPDATE_BRANCH_PROTECTION",
    "GITHUB_DELETE_BRANCH_PROTECTION",
    "GITHUB_DELETE_A_REPOSITORY",
    "GITHUB_TRANSFER_A_REPOSITORY",
    "GITHUB_REMOVE_A_REPOSITORY_COLLABORATOR",
    "GITHUB_REMOVE_AN_ORGANIZATION_MEMBER",
    "GITHUB_DELETE_A_DEPLOY_KEY",
    "GITHUB_DELETE_A_REPOSITORY_SECRET",
    "GITHUB_DELETE_AN_ORGANIZATION_SECRET",
    "GITHUB_DELETE_AN_ENVIRONMENT_SECRET",
    "GITHUB_DELETE_AN_ENVIRONMENT",
    "GITHUB_CREATE_A_DEPLOYMENT",
    "GITHUB_DELETE_A_DEPLOYMENT",
    "GITHUB_FORCE_CANCEL_A_WORKFLOW_RUN",
    "GITHUB_DELETE_A_WORKFLOW_RUN",
    "GITHUB_UPDATE_A_REPOSITORY_RULESET",
    "GITHUB_UPDATE_A_REPOSITORY",
    "GITHUB_REMOVE_A_REPOSITORY_FROM_A_TEAM",
    "GITHUB_DELETE_A_REPOSITORY_RULESET",
    "GITHUB_DELETE_A_REPOSITORY_WEBHOOK",
    "GITHUB_DELETE_A_RELEASE",
    "GITHUB_DELETE_A_RELEASE_ASSET",
    "GITHUB_DELETE_A_PACKAGE_FOR_AN_ORGANIZATION",
    "GITHUB_DELETE_A_PACKAGE_VERSION_FOR_AN_ORGANIZATION",
    "GITHUB_DELETE_A_REFERENCE",
    "GITHUB_DISABLE_A_WORKFLOW",
    "GITHUB_CREATE_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER",
]

REDDIT_DESTRUCTIVE_TOOLS: list[str] = [
    "REDDIT_CREATE_REDDIT_POST",
    "REDDIT_DELETE_REDDIT_COMMENT",
    "REDDIT_DELETE_REDDIT_POST",
    "REDDIT_POST_REDDIT_COMMENT",
]

AIRTABLE_DESTRUCTIVE_TOOLS: list[str] = [
    "AIRTABLE_DELETE_COMMENT",
    "AIRTABLE_DELETE_MULTIPLE_RECORDS",
    "AIRTABLE_DELETE_RECORD",
]

LINEAR_DESTRUCTIVE_TOOLS: list[str] = [
    "LINEAR_DELETE_LINEAR_ISSUE",
    "LINEAR_RUN_QUERY_OR_MUTATION",
]

SLACK_DESTRUCTIVE_TOOLS: list[str] = [
    "SLACK_DELETES_A_MESSAGE_FROM_A_CHAT",
    "SLACK_UPDATES_A_SLACK_MESSAGE",
    "SLACK_DELETE_A_SCHEDULED_MESSAGE_IN_A_CHAT",
    "SLACK_DELETE_A_FILE_BY_ID",
    "SLACK_DELETE_A_COMMENT_ON_A_FILE",
    "SLACK_DELETE_CANVAS",
    "SLACK_EDIT_CANVAS",
    "SLACK_DELETE_A_PUBLIC_OR_PRIVATE_CHANNEL",
    "SLACK_ARCHIVE_A_SLACK_CONVERSATION",
    "SLACK_CONVERT_PUBLIC_CHANNEL_TO_PRIVATE",
    "SLACK_RENAME_A_CONVERSATION",
    "SLACK_RENAME_A_SLACK_CHANNEL",
    "SLACK_REMOVE_A_USER_FROM_A_CONVERSATION",
    "SLACK_REMOVE_USER_FROM_WORKSPACE",
    "SLACK_ENABLE_PUBLIC_SHARING_OF_A_FILE",
    "SLACK_REVOKE_PUBLIC_SHARING_ACCESS_FOR_A_FILE",
    "SLACK_RESET_USER_SESSIONS",
    "SLACK_RESTRICT_APP_INSTALLATION",
    "SLACK_SET_ADMIN_USER",
    "SLACK_SET_WORKSPACE_OWNER",
    "SLACK_DISABLE_AN_EXISTING_SLACK_USER_GROUP",
    "SLACK_UPDATE_AN_EXISTING_SLACK_USER_GROUP",
    "SLACK_UPDATE_USER_GROUP_MEMBERS",
    "SLACK_SET_DEFAULT_CHANNELS",
    "SLACK_SET_WORKSPACES_FOR_CHANNEL",
    "SLACK_SET_CONVERSATION_PREFS",
    "SLACK_SET_WORKSPACE_NAME",
    "SLACK_SET_WORKSPACE_DESCRIPTION",
    "SLACK_SET_WORKSPACE_ICON",
    "SLACK_REMOVE_A_REMOTE_FILE",
    "SLACK_UPDATES_AN_EXISTING_REMOTE_FILE",
    "SLACK_DELETE_A_SLACK_REMINDER",
    "SLACK_REMOVE_EMOJI",
    "SLACK_RENAME_AN_EMOJI",
    "SLACK_RENAME_A_SLACK_CHANNEL",
    "SLACK_SCHEDULE_MESSAGE",
    "SLACK_SEND_EPHEMERAL_MESSAGE",
    "SLACK_SEND_MESSAGE",
]

HUBSPOT_DESTRUCTIVE_TOOLS: list[str] = [
    "HUBSPOT_DELETE_CALL",
    "HUBSPOT_DELETE_CALLING_EXTENSION_SETTINGS",
    "HUBSPOT_DELETE_CAMPAIGN",
    "HUBSPOT_DELETE_COMPANY_GDPR",
    "HUBSPOT_DELETE_CONTACT_GDPR",
    "HUBSPOT_DELETE_LINE_ITEMS_GDPR",
    "HUBSPOT_DELETE_MARKETING_EMAIL",
    "HUBSPOT_DELETE_PIPELINE",
    "HUBSPOT_DELETE_PIPELINE_STAGE",
    "HUBSPOT_DELETE_SCHEMA",
    "HUBSPOT_DELETE_TIMELINE_EVENT_TEMPLATE",
    "HUBSPOT_DELETE_VIDEO_CONFERENCING_APP_SETTINGS",
    "HUBSPOT_DELETE_WORKFLOW",
    "HUBSPOT_PERMANENTLY_DELETE_CONTACT_VIA_GDPR",
    "HUBSPOT_PUBLISH_MARKETING_EMAIL",
    "HUBSPOT_PURGE_SCHEMA",
]

GOOGLETASKS_DESTRUCTIVE_TOOLS: list[str] = [
    "GOOGLETASKS_BATCH_EXECUTE",
    "GOOGLETASKS_CLEAR_TASKS",
    "GOOGLETASKS_DELETE_TASK",
    "GOOGLETASKS_DELETE_TASK_LIST",
]

TODOIST_DESTRUCTIVE_TOOLS: list[str] = [
    "TODOIST_DELETE_COMMENT",
    "TODOIST_DELETE_LABEL_V1",
    "TODOIST_DELETE_PROJECT2",
    "TODOIST_DELETE_SECTION2",
    "TODOIST_DELETE_TASK",
    "TODOIST_DELETE_TASK_V1",
    "TODOIST_DELETE_UPLOAD",
    "TODOIST_REMOVE_SHARED_LABEL_V1",
    "TODOIST_SYNC",
]

MICROSOFT_TEAMS_DESTRUCTIVE_TOOLS: list[str] = [
    "MICROSOFT_TEAMS_DELETE_CHANNEL",
    "MICROSOFT_TEAMS_DELETE_TEAM",
    "MICROSOFT_TEAMS_POST_MESSAGE_REPLY",
    "MICROSOFT_TEAMS_SEND_ACTIVITY_NOTIFICATION",
    "MICROSOFT_TEAMS_TEAMS_POST_CHANNEL_MESSAGE",
    "MICROSOFT_TEAMS_TEAMS_POST_CHAT_MESSAGE",
    "MICROSOFT_TEAMS_TEAMS_POST_MESSAGE_REPLY",
]

ZOOM_DESTRUCTIVE_TOOLS: list[str] = [
    "ZOOM_CHAT",
    "ZOOM_DELETE_A_MEETING",
    "ZOOM_DELETE_IQ_CONVERSATION",
    "ZOOM_DELETE_IQ_CONVERSATION_COMMENT",
    "ZOOM_DELETE_IQ_DEAL_ACTIVITIES",
    "ZOOM_DELETE_MEETING_RECORDINGS",
    "ZOOM_DELETE_PROJECT",
    "ZOOM_DELETE_RECORDING_FILE",
    "ZOOM_DELETE_WHITEBOARD",
    "ZOOM_DELETE_ZRA_CONVERSATION",
    "ZOOM_DELETE_ZRA_CONVERSATION_COMMENT",
    "ZOOM_DELETE_ZRA_CRM_SETTINGS",
    "ZOOM_DELETE_ZRA_DEAL_ACTIVITIES",
]

GOOGLEMEET_DESTRUCTIVE_TOOLS: list[str] = []

GOOGLE_MAPS_DESTRUCTIVE_TOOLS: list[str] = []

ASANA_DESTRUCTIVE_TOOLS: list[str] = [
    "ASANA_DELETE_ALLOCATION",
    "ASANA_DELETE_ATTACHMENT",
    "ASANA_DELETE_CUSTOM_FIELD",
    "ASANA_DELETE_MEMBERSHIP",
    "ASANA_DELETE_PROJECT",
    "ASANA_DELETE_PROJECT_BRIEF",
    "ASANA_DELETE_PROJECT_STATUS",
    "ASANA_DELETE_SECTION",
    "ASANA_DELETE_STATUS_UPDATE",
    "ASANA_DELETE_STORY",
    "ASANA_DELETE_TAG",
    "ASANA_DELETE_TASK",
    "ASANA_SUBMIT_PARALLEL_REQUESTS",
]

TRELLO_DESTRUCTIVE_TOOLS: list[str] = [
    "TRELLO_DELETE_ACTION",
    "TRELLO_DELETE_BOARD",
    "TRELLO_DELETE_CARDS_BY_ID_CARD",
    "TRELLO_DELETE_CARD_ATTACHMENT",
    "TRELLO_DELETE_CARD_CHECKLIST",
    "TRELLO_DELETE_CARD_COMMENT",
    "TRELLO_DELETE_CHECKLISTS_BY_ID_CHECKLIST",
    "TRELLO_DELETE_CHECKLIST_ITEM",
    "TRELLO_DELETE_LABELS_BY_ID_LABEL",
    "TRELLO_DELETE_MEMBER_BOARD_BACKGROUND",
    "TRELLO_DELETE_MEMBER_CUSTOM_STICKER",
    "TRELLO_DELETE_MEMBER_SAVED_SEARCH",
    "TRELLO_DELETE_ORGANIZATIONS_BY_ID_ORG",
    "TRELLO_DELETE_TOKENS_BY_TOKEN",
    "TRELLO_DELETE_TOKENS_WEBHOOKS_BY_TOKEN_BY_ID_WEBHOOK",
    "TRELLO_DELETE_WEBHOOKS_BY_ID_WEBHOOK",
]

INSTAGRAM_DESTRUCTIVE_TOOLS: list[str] = [
    "INSTAGRAM_CREATE_POST",
    "INSTAGRAM_DELETE_COMMENT",
    "INSTAGRAM_DELETE_MESSENGER_PROFILE",
    "INSTAGRAM_POST_IG_COMMENT_REPLIES",
    "INSTAGRAM_POST_IG_MEDIA_COMMENTS",
    "INSTAGRAM_POST_IG_USER_MEDIA_PUBLISH",
    "INSTAGRAM_POST_IG_USER_MENTIONS",
    "INSTAGRAM_REPLY_TO_COMMENT",
    "INSTAGRAM_SEND_IMAGE",
    "INSTAGRAM_SEND_TEXT_MESSAGE",
]

CLICKUP_DESTRUCTIVE_TOOLS: list[str] = [
    "CLICKUP_CREATE_CHAT_MESSAGE",
    "CLICKUP_CREATE_DIRECT_MESSAGE_CHANNEL",
    "CLICKUP_CREATE_REPLY_MESSAGE",
    "CLICKUP_DELETE_CHAT_CHANNEL",
    "CLICKUP_DELETE_CHAT_MESSAGE",
    "CLICKUP_DELETE_CHECKLIST",
    "CLICKUP_DELETE_CHECKLIST_ITEM",
    "CLICKUP_DELETE_COMMENT",
    "CLICKUP_DELETE_FOLDER",
    "CLICKUP_DELETE_GOAL",
    "CLICKUP_DELETE_KEY_RESULT",
    "CLICKUP_DELETE_LIST",
    "CLICKUP_DELETE_SPACE",
    "CLICKUP_DELETE_TASK",
    "CLICKUP_DELETE_TEAM",
    "CLICKUP_DELETE_TIME_ENTRY",
    "CLICKUP_DELETE_TIME_TRACKED",
    "CLICKUP_DELETE_VIEW",
    "CLICKUP_DELETE_WEBHOOK",
]

# Cancelling/declining a booking emails the attendee and cannot be taken back;
# booking creation is not gated, matching GOOGLECALENDAR (create is routine).
CALCOM_DESTRUCTIVE_TOOLS: list[str] = [
    "CAL_CANCEL_BOOKING_VIA_UID",
    "CAL_DECLINE_BOOKING_WITH_REASON",
    "CAL_DELETE_EVENT_TYPE_BY_ID",
    "CAL_DELETE_EVENT_TYPE_IN_TEAM",
    "CAL_DELETE_ORGANIZATION_MEMBERSHIP",
    "CAL_DELETE_SCHEDULE_BY_ID",
    "CAL_DELETE_TEAM_BY_ID",
    "CAL_DELETE_TEAM_EVENT_TYPE_IN_ORGANIZATION",
    "CAL_DELETE_TEAM_FROM_ORGANIZATION",
    "CAL_DELETE_USER_FROM_ORGANIZATION",
    "CAL_DELETE_USER_SCHEDULE",
    "CAL_SAVE_STRIPE_DETAILS",
]

# POST_INVITEE books a slot on someone's calendar and emails them; the org
# invitation emails a third party.
CALENDLY_DESTRUCTIVE_TOOLS: list[str] = [
    "CALENDLY_CANCEL_SCHEDULED_EVENT",
    "CALENDLY_DELETE_INVITEE_DATA",
    "CALENDLY_DELETE_ORGANIZATION_MEMBERSHIP",
    "CALENDLY_DELETE_SCHEDULED_EVENT_DATA",
    "CALENDLY_ORGANIZATION_INVITATION",
    "CALENDLY_POST_INVITEE",
    "CALENDLY_REMOVE_USER_FROM_ORGANIZATION",
]

# Plain OUTLOOK_DELETE_MESSAGE moves mail to Deleted Items (recoverable), so only
# the *_PERMANENTLY / PERMANENT_DELETE variants gate. Calendar deletes/cancels
# notify attendees, and calendar permissions expose contents (cf. GOOGLEDRIVE).
OUTLOOK_DESTRUCTIVE_TOOLS: list[str] = [
    "OUTLOOK_CANCEL_CALENDAR_EVENT",
    "OUTLOOK_CANCEL_CALENDAR_GROUP_CALENDAR_EVENT",
    "OUTLOOK_CANCEL_EVENT",
    "OUTLOOK_CREATE_CALENDAR_PERMISSION",
    "OUTLOOK_CREATE_ME_CALENDAR_PERMISSION",
    "OUTLOOK_DECLINE_EVENT",
    "OUTLOOK_DELETE_CALENDAR",
    "OUTLOOK_DELETE_CALENDAR_EVENT",
    "OUTLOOK_DELETE_CALENDAR_EVENT_FROM_SPECIFIC_CALENDAR",
    "OUTLOOK_DELETE_CALENDAR_GROUP",
    "OUTLOOK_DELETE_CALENDAR_GROUP_EVENT_PERMANENTLY",
    "OUTLOOK_DELETE_CALENDAR_PERMANENTLY",
    "OUTLOOK_DELETE_CHILD_CONTACT_FOLDER_PERMANENTLY",
    "OUTLOOK_DELETE_CONTACT_FOLDER_PERMANENTLY",
    "OUTLOOK_DELETE_CONTACT_FROM_CHILD_FOLDER_PERMANENTLY",
    "OUTLOOK_DELETE_CONTACT_FROM_FOLDER_PERMANENTLY",
    "OUTLOOK_DELETE_CONTACT_PERMANENTLY",
    "OUTLOOK_DELETE_EVENT_PERMANENTLY",
    "OUTLOOK_DELETE_ME_MAIL_FOLDER_CHILD_FOLDER_PERMANENTLY",
    "OUTLOOK_DELETE_USER_CALENDAR_EVENT_PERMANENTLY",
    "OUTLOOK_DELETE_USER_CHILD_FOLDER_MESSAGE_PERMANENTLY",
    "OUTLOOK_DELETE_USER_EVENT_PERMANENTLY",
    "OUTLOOK_DELETE_USER_MAIL_FOLDER_PERMANENTLY",
    "OUTLOOK_FORWARD_MESSAGE",
    "OUTLOOK_FORWARD_USER_CALENDAR_EVENT",
    "OUTLOOK_PERMANENT_DELETE_MESSAGE",
    "OUTLOOK_REPLY_EMAIL",
    "OUTLOOK_SEND_DRAFT",
    "OUTLOOK_SEND_EMAIL",
]

JIRA_DESTRUCTIVE_TOOLS: list[str] = [
    "JIRA_DELETE_ATTACHMENT",
    "JIRA_DELETE_COMMENT",
    "JIRA_DELETE_ISSUE",
    "JIRA_DELETE_VERSION",
    "JIRA_DELETE_WORKLOG",
    "JIRA_SEND_NOTIFICATION_FOR_ISSUE",
]

# DROPBOX_DELETE_FILE / DELETE_BATCH are recoverable (Dropbox keeps deleted files
# restorable via DROPBOX_RESTORE_FILE), so they stay ungated like Drive trash.
# Sharing gates for the same reason GOOGLEDRIVE_CREATE_PERMISSION does.
DROPBOX_DESTRUCTIVE_TOOLS: list[str] = [
    "DROPBOX_ADD_FILE_MEMBER",
    "DROPBOX_ADD_FOLDER_MEMBER_ACTION",
    "DROPBOX_ADD_TEAM_MEMBERS",
    "DROPBOX_CREATE_SHARED_LINK",
    "DROPBOX_DELETE_ALL_CLOSED_FILE_REQUESTS",
    "DROPBOX_DELETE_FILE_REQUESTS",
    "DROPBOX_DELETE_MANUAL_CONTACTS_BATCH",
    "DROPBOX_DELETE_TEAM_FOLDER_PERMANENTLY",
    "DROPBOX_DELETE_TEAM_GROUP",
    "DROPBOX_SEND_TEAM_MEMBER_WELCOME_EMAIL",
    "DROPBOX_SHARE_FOLDER",
]
