/**
 * Utilities for writing and reading environment variable files.
 * @module env-writer
 */

import * as fs from 'fs';
import * as path from 'path';

/**
 * Key-value map of environment variables.
 */
export interface EnvValues {
  [key: string]: string;
}

/**
 * Writes environment variables to a .env file in the repository.
 * Groups variables by their prefix for better organization.
 * @param repoPath - Path to the repository root
 * @param values - Object containing environment variable key-value pairs
 * @example
 * writeEnvFile('./my-repo', {
 *   MONGO_DB: 'mongodb://localhost:27017/gaia',
 *   REDIS_URL: 'redis://localhost:6379'
 * });
 */
export function writeEnvFile(repoPath: string, values: EnvValues): void {
  const envPath = path.join(repoPath, '.env');
  
  // Build .env content with categories
  const lines: string[] = [
    '# GAIA Environment Configuration',
    '# Generated by GAIA CLI',
    `# Created: ${new Date().toISOString()}`,
    '',
  ];
  
  // Group by prefix for organization
  const grouped: Map<string, string[]> = new Map();
  
  for (const [key, value] of Object.entries(values)) {
    const prefix = key.split('_')[0] || key;
    if (!grouped.has(prefix)) {
      grouped.set(prefix, []);
    }
    grouped.get(prefix)!.push(`${key}=${value}`);
  }
  
  // Write grouped variables
  for (const [prefix, vars] of grouped.entries()) {
    lines.push(`# ${prefix} Configuration`);
    lines.push(...vars);
    lines.push('');
  }
  
  fs.writeFileSync(envPath, lines.join('\n'), 'utf-8');
}

/**
 * Checks if a .env file already exists in the repository.
 * @param repoPath - Path to the repository root
 * @returns True if .env file exists, false otherwise
 * @internal Reserved for future use (updating existing env files)
 */
export function envFileExists(repoPath: string): boolean {
  const envPath = path.join(repoPath, '.env');
  return fs.existsSync(envPath);
}

/**
 * Reads and parses an existing .env file.
 * @param repoPath - Path to the repository root
 * @returns Object containing environment variable key-value pairs
 * @internal Reserved for future use (updating existing env files)
 */
export function readEnvFile(repoPath: string): EnvValues {
  const envPath = path.join(repoPath, '.env');
  
  if (!fs.existsSync(envPath)) {
    return {};
  }
  
  const content = fs.readFileSync(envPath, 'utf-8');
  const values: EnvValues = {};
  
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key) {
        values[key.trim()] = valueParts.join('=').trim();
      }
    }
  }
  
  return values;
}
