import * as fs from "fs";
import * as path from "path";
import {
  getWebInfrastructureDefaults,
  parseWebEnv,
  type SetupMode,
} from "./env-parser.js";

export interface EnvValues {
  [key: string]: string;
}

/**
 * Parse a raw `.env` body into KEY→VALUE pairs. Comments/blanks are skipped,
 * surrounding quotes are stripped; blank values are omitted (a half-written
 * entry counts as unset).
 */
export function parseEnvFileValues(content: string | null): EnvValues {
  const values: EnvValues = {};
  if (!content) return values;

  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx <= 0) continue;
    const key = trimmed.substring(0, eqIdx).trim();
    const value = trimmed
      .substring(eqIdx + 1)
      .trim()
      .replace(/^["']|["']$/g, "");
    if (key && value) values[key] = value;
  }
  return values;
}

/**
 * Environment files carry generated machine secrets (AGENT_SECRET et al.), so
 * they must never be group/world-readable.
 */
const ENV_FILE_MODE = 0o600;

function backupIfExists(filePath: string): void {
  if (fs.existsSync(filePath)) {
    const backupPath = `${filePath}.bak`;
    fs.copyFileSync(filePath, backupPath);
    // copyFileSync lands on default perms; the backup holds the previous
    // generation of secrets, so it gets the same owner-only bar.
    fs.chmodSync(backupPath, ENV_FILE_MODE);
  }
}

/**
 * Write an env file locked to 0600. `writeFileSync`'s mode option only applies
 * at creation — a pre-existing file keeps its old mode — so the explicit chmod
 * also tightens files left world-readable by older CLI versions.
 */
function writeFileOwnerOnly(filePath: string, contents: string): void {
  fs.writeFileSync(filePath, contents, {
    encoding: "utf-8",
    mode: ENV_FILE_MODE,
  });
  fs.chmodSync(filePath, ENV_FILE_MODE);
}

export function writeEnvFile(repoPath: string, values: EnvValues): void {
  const envPath = path.join(repoPath, ".env");
  backupIfExists(envPath);

  const lines: string[] = [
    "# GAIA Environment Configuration",
    "# Generated by GAIA CLI",
    `# Created: ${new Date().toISOString()}`,
    "",
  ];

  const KNOWN_PREFIXES = [
    "MONGO",
    "REDIS",
    "POSTGRES",
    "CHROMADB",
    "RABBITMQ",
    "WORKOS",
    "GOOGLE",
    "OPENAI",
    "INFISICAL",
    "LANGSMITH",
    "DISCORD",
    "SLACK",
    "TELEGRAM",
    "CLOUDINARY",
    "COMPOSIO",
    "FIRECRAWL",
    "LIVEKIT",
    "DEEPGRAM",
    "ELEVENLABS",
    "RESEND",
    "SENTRY",
    "POSTHOG",
    "E2B",
    "DODO",
    "NEXT_PUBLIC",
    "GAIA",
  ];

  function getGroupKey(key: string): string {
    // Check known prefixes (longest match first for multi-word prefixes like NEXT_PUBLIC)
    for (const prefix of KNOWN_PREFIXES) {
      if (key === prefix || key.startsWith(`${prefix}_`)) {
        return prefix;
      }
    }
    // Single-word vars (no underscore) go into "Core"
    const parts = key.split("_");
    if (parts.length === 1) {
      return "Core";
    }
    // Unknown vars: group by first underscore segment
    return parts[0] || "Core";
  }

  const grouped: Map<string, string[]> = new Map();

  for (const [key, value] of Object.entries(values)) {
    const group = getGroupKey(key);
    if (!grouped.has(group)) {
      grouped.set(group, []);
    }
    // Quote value if it contains spaces, #, or other special chars
    const needsQuoting = /[\s#"'\\]/.test(value) || value === "";
    const quotedValue = needsQuoting
      ? `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
      : value;
    grouped.get(group)!.push(`${key}=${quotedValue}`);
  }

  for (const [prefix, vars] of grouped.entries()) {
    lines.push(`# ${prefix} Configuration`);
    lines.push(...vars);
    lines.push("");
  }

  writeFileOwnerOnly(envPath, lines.join("\n"));
}

export function writeWebEnvFile(
  repoPath: string,
  mode: SetupMode,
  portOverrides?: Record<number, number>,
): void {
  const webEnvPath = path.join(repoPath, "apps", "web", ".env.local");
  backupIfExists(webEnvPath);

  // Parse existing .env to discover all vars
  const discoveredVars = parseWebEnv(repoPath);
  const infraDefaults = getWebInfrastructureDefaults(mode, portOverrides);

  const lines: string[] = [
    "# GAIA Web App Environment Configuration",
    "# Generated by GAIA CLI",
    `# Created: ${new Date().toISOString()}`,
    "",
  ];

  // Group vars by category
  const categories = new Map<string, { name: string; value: string }[]>();

  for (const v of discoveredVars) {
    if (!categories.has(v.category)) {
      categories.set(v.category, []);
    }
    // Use infrastructure default if available, otherwise use discovered value
    const value = infraDefaults[v.name] ?? v.value;
    categories.get(v.category)!.push({ name: v.name, value });
  }

  // If no vars discovered, write infrastructure defaults
  if (discoveredVars.length === 0) {
    lines.push("# Core URLs");
    for (const [key, value] of Object.entries(infraDefaults)) {
      lines.push(`${key}=${value}`);
    }
    lines.push("");
  } else {
    for (const [category, vars] of categories.entries()) {
      lines.push(`# ${category}`);
      for (const { name, value } of vars) {
        lines.push(`${name}=${value}`);
      }
      lines.push("");
    }
  }

  writeFileOwnerOnly(webEnvPath, lines.join("\n"));
}

const DOCKER_PORT_VAR_MAP: Record<number, string> = {
  8000: "API_HOST_PORT",
  5432: "POSTGRES_HOST_PORT",
  6379: "REDIS_HOST_PORT",
  27017: "MONGO_HOST_PORT",
  5672: "RABBITMQ_HOST_PORT",
  15672: "RABBITMQ_MGMT_PORT",
  8080: "CHROMADB_HOST_PORT",
  8083: "MONGO_EXPRESS_HOST_PORT",
  3000: "WEB_HOST_PORT",
};

export function writeDockerComposeEnv(
  repoRoot: string,
  portOverrides: Record<number, number>,
  mode?: SetupMode,
): void {
  const envPath = path.join(repoRoot, "infra", "docker", ".env");
  backupIfExists(envPath);

  // Merge-don't-clobber: preserve existing custom ports, domains and unknown
  // keys. Rerunning `gaia up` with no new conflicts (portOverrides={}) must not
  // erase a previous `CHROMADB_HOST_PORT=18080` or a hand-edited
  // `NEXT_PUBLIC_APP_URL=https://gaia.example.com`.
  const existingValues: EnvValues = fs.existsSync(envPath)
    ? parseEnvFileValues(fs.readFileSync(envPath, "utf-8"))
    : {};
  const merged: EnvValues = { ...existingValues };

  for (const [original, replacement] of Object.entries(portOverrides)) {
    const origPort = Number(original);
    const varName = DOCKER_PORT_VAR_MAP[origPort];
    if (varName) {
      merged[varName] = String(replacement);
    }
  }

  // In selfhost mode, write the web runtime URL so docker-compose.selfhost.yml
  // passes it to the container, whose entrypoint rewrites the baked-in
  // placeholder API URL inside the JS bundle at start (single mechanism —
  // local builds bake the placeholder, runtime always wins).
  // Preserve an explicit non-localhost domain (reverse-proxy) across reruns.
  if (mode === "selfhost") {
    const existingUrl = existingValues["NEXT_PUBLIC_APP_URL"];
    const isCustomDomain =
      !!existingUrl &&
      !existingUrl.includes("localhost") &&
      !existingUrl.includes("127.0.0.1");
    if (!isCustomDomain) {
      const webPort =
        portOverrides[3000] ??
        (existingValues["WEB_HOST_PORT"]
          ? Number(existingValues["WEB_HOST_PORT"])
          : 3000);
      const safePort =
        Number.isFinite(webPort) && webPort > 0 && webPort <= 65535 ? webPort : 3000;
      merged["NEXT_PUBLIC_APP_URL"] = `http://localhost:${safePort}`;
    }
  }

  const lines: string[] = [
    "# Docker Compose environment overrides",
    "# Generated by GAIA CLI",
    `# Created: ${new Date().toISOString()}`,
    "",
  ];

  for (const [key, value] of Object.entries(merged)) {
    lines.push(`${key}=${value}`);
  }

  lines.push("");
  writeFileOwnerOnly(envPath, lines.join("\n"));
}

/**
 * Convert port overrides (e.g. {5432: 5433, 8080: 8081}) to Docker Compose
 * environment variable names (e.g. {POSTGRES_HOST_PORT: "5433", CHROMADB_HOST_PORT: "8081"}).
 * These can be passed as shell env vars to `docker compose`, where they take
 * highest priority over .env files and defaults in docker-compose.yml.
 */
export function portOverridesToDockerEnv(
  portOverrides: Record<number, number>,
): Record<string, string> {
  const env: Record<string, string> = {};
  for (const [original, replacement] of Object.entries(portOverrides)) {
    const origPort = Number(original);
    const varName = DOCKER_PORT_VAR_MAP[origPort];
    if (varName) {
      env[varName] = String(replacement);
    }
  }
  return env;
}

/**
 * Patch docker-compose.yml to use variable substitution for port mappings.
 * Converts hardcoded ports like `"5432:5432"` into `"${POSTGRES_HOST_PORT:-5432}:5432"`.
 * This is needed because older versions of the compose file have hardcoded ports,
 * and the .env override mechanism only works with variable substitution syntax.
 */
export function patchDockerComposePorts(repoRoot: string): void {
  const composePath = path.join(
    repoRoot,
    "infra",
    "docker",
    "docker-compose.yml",
  );
  if (!fs.existsSync(composePath)) return;

  let content = fs.readFileSync(composePath, "utf-8");

  const PORT_PATTERNS: Array<{
    varName: string;
    hostPort: number;
    containerPort: number;
  }> = [
    { varName: "API_HOST_PORT", hostPort: 8000, containerPort: 80 },
    { varName: "CHROMADB_HOST_PORT", hostPort: 8080, containerPort: 8000 },
    { varName: "POSTGRES_HOST_PORT", hostPort: 5432, containerPort: 5432 },
    { varName: "REDIS_HOST_PORT", hostPort: 6379, containerPort: 6379 },
    { varName: "MONGO_HOST_PORT", hostPort: 27017, containerPort: 27017 },
    { varName: "RABBITMQ_HOST_PORT", hostPort: 5672, containerPort: 5672 },
    {
      varName: "MONGO_EXPRESS_HOST_PORT",
      hostPort: 8083,
      containerPort: 8081,
    },
    { varName: "WEB_HOST_PORT", hostPort: 3000, containerPort: 3000 },
  ];

  let changed = false;
  for (const { varName, hostPort, containerPort } of PORT_PATTERNS) {
    const hardcoded = `"${hostPort}:${containerPort}"`;
    const variable = `"\${${varName}:-${hostPort}}:${containerPort}"`;
    if (content.includes(hardcoded)) {
      content = content.replaceAll(hardcoded, variable);
      changed = true;
    }
  }
  // RabbitMQ management port is 15672 on both sides; handle without PORT_PATTERNS
  // to keep the main table focused on the 8 original ports.
  {
    const hardcoded = `"15672:15672"`;
    const variable = `"\${RABBITMQ_MGMT_PORT:-15672}:15672"`;
    if (content.includes(hardcoded)) {
      content = content.replaceAll(hardcoded, variable);
      changed = true;
    }
  }

  if (changed) {
    fs.writeFileSync(composePath, content, "utf-8");
  }
}

const DOCKER_PORT_VAR_TO_PORT: Record<string, number> = {
  API_HOST_PORT: 8000,
  POSTGRES_HOST_PORT: 5432,
  REDIS_HOST_PORT: 6379,
  MONGO_HOST_PORT: 27017,
  RABBITMQ_HOST_PORT: 5672,
  RABBITMQ_MGMT_PORT: 15672,
  CHROMADB_HOST_PORT: 8080,
  MONGO_EXPRESS_HOST_PORT: 8083,
  WEB_HOST_PORT: 3000,
};

export function readDockerComposePortOverrides(
  repoRoot: string,
): Record<number, number> {
  const envPath = path.join(repoRoot, "infra", "docker", ".env");
  const overrides: Record<number, number> = {};

  if (!fs.existsSync(envPath)) {
    return overrides;
  }

  const content = fs.readFileSync(envPath, "utf-8");
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#")) {
      const [key, ...valueParts] = trimmed.split("=");
      if (key && DOCKER_PORT_VAR_TO_PORT[key]) {
        const cleaned = valueParts
          .join("=")
          .trim()
          .replace(/^["']|["']$/g, "");
        const port = Number(cleaned);
        if (!Number.isNaN(port) && port > 0 && port <= 65535) {
          overrides[DOCKER_PORT_VAR_TO_PORT[key]] = port;
        }
      }
    }
  }

  return overrides;
}
