/**
 * A collection of friendly greetings for when users mention GAIA without a message.
 * One is randomly selected to keep interactions fresh and engaging.
 */
export const GREETINGS = [
  "How can I help you?",
  "What's on your mind?",
  "Hey there! What can I do for you?",
  "I'm listening! What do you need?",
  "What brings you here today?",
  "Ready when you are! What's up?",
  "I'm here! How can I assist?",
  "What would you like to know?",
  "Fire away! What can I help with?",
  "What can I do for you today?",
  "Hello! What's the question?",
  "I'm all ears! What do you need?",
  "What's happening? Need help?",
  "Talk to me! What's up?",
  "How may I assist you?",
  "What's the task at hand?",
  "Ready to help! What is it?",
  "I'm here for you! What's going on?",
  "What adventure are we on today?",
  "How can I make your day easier?",
  "What puzzle can I help solve?",
  "Shoot! What do you need?",
  "What's the challenge today?",
  "I'm at your service! What's needed?",
  "What question can I answer?",
  "Tell me what you're working on!",
  "What's the mission?",
  "How can I be useful right now?",
  "What's the word?",
  "I'm ready! What do you have for me?",
  "What can I tackle for you?",
  "Lay it on me! What's up?",
  "What would you like to explore?",
  "How can I support you today?",
  "What's brewing? How can I help?",
  "I'm here! What's the plan?",
  "What shall we work on?",
  "Hit me with it! What do you need?",
  "What's cooking? Need a hand?",
  "Ready to roll! What's up?",
  "What can I dig into for you?",
  "I'm online and ready! What's happening?",
  "What mystery shall we solve?",
  "How can I lighten your load?",
  "What's the next step I can help with?",
  "I'm tuned in! What do you want to know?",
  "What brings you to me today?",
  "Ready and waiting! What's the ask?",
  "What can I research for you?",
  "Tell me your thoughts!",
  "What information do you need?",
  "I'm powered up! How can I help?",
  "What problem are we solving?",
  "What's the topic today?",
  "I'm on standby! What now?",
  "What task can I handle?",
  "What are you curious about?",
  "How can I make things better?",
  "What would you like me to do?",
  "I'm ready to dive in! What is it?",
  "What question is on your mind?",
  "How may I be of service?",
  "What can I answer for you?",
  "Tell me everything! What's up?",
  "What challenge shall we tackle?",
  "I'm activated! What do you need?",
  "What's your request?",
  "How can I contribute right now?",
  "What's the issue I can help with?",
  "I'm listening closely! What is it?",
  "What shall I look into?",
  "Ready for action! What's needed?",
  "What's the goal today?",
  "How can I save you time?",
  "What information can I find?",
  "I'm here to help! What's going on?",
  "What's the situation?",
  "Tell me what you're thinking!",
  "What can I figure out for you?",
  "I'm engaged! What do you want?",
  "What's the task you have in mind?",
  "How can I assist with your work?",
  "What shall we accomplish?",
  "I'm focused! What's the need?",
  "What can I help you understand?",
  "Ready to jump in! What is it?",
  "What's on the agenda?",
  "How can I make this easier?",
  "What would you like to discuss?",
  "I'm available! What's happening?",
  "What can I research or find?",
  "Tell me your question!",
  "What knowledge can I share?",
  "I'm primed and ready! What's up?",
  "What shall I help you with?",
  "How can I be helpful today?",
  "What's the next thing I can do?",
  "I'm standing by! What do you need?",
  "What can I clarify for you?",
  "Ready to assist! What's the matter?",
];

/**
 * Returns a random greeting from the collection.
 */
export function getRandomGreeting(): string {
  return GREETINGS[Math.floor(Math.random() * GREETINGS.length)];
}
