/**
 * Gaia Icons — React Native
 *
 * React Native wrappers for gaia icons using react-native-svg and
 * pre-extracted SVG path data.
 *
 * Covers both solid (tool categories) and stroke (UI) icons.
 * Path data generated by: pnpm tsx apps/web/scripts/extract-icon-paths.ts
 *
 * Import pattern:
 *   import { Brain02Icon, ArrowLeft01Icon } from "@icons";
 */

import iconPathData from "@shared/ts/src/icons/icon-paths.generated.json";
import type React from "react";
import Svg, { Path } from "react-native-svg";

export interface IconProps {
  size?: number;
  width?: number;
  height?: number;
  color?: string;
  strokeWidth?: number;
  style?: object;
  className?: string;
}

type IconName = keyof typeof iconPathData;
export type GaiaIconComponent = React.ComponentType<IconProps>;

function createIcon(name: IconName) {
  const { viewBox, paths } = iconPathData[name];
  return function GaiaIcon({
    size = 24,
    width,
    height,
    color = "#ffffff",
    style,
  }: IconProps) {
    return (
      <Svg
        width={width ?? size}
        height={height ?? size}
        viewBox={viewBox}
        style={style}
      >
        {paths.map((d, i) => (
          // biome-ignore lint/suspicious/noArrayIndexKey: stable path list per icon
          <Path key={i} d={d} fill={color} />
        ))}
      </Svg>
    );
  };
}

export const gaiaIconRegistry = Object.fromEntries(
  (Object.keys(iconPathData) as IconName[]).map((name) => [
    name,
    createIcon(name),
  ]),
) as Record<IconName, GaiaIconComponent>;

export function getGaiaIcon(name: string): GaiaIconComponent | undefined {
  return gaiaIconRegistry[name as IconName];
}

export const Add01Icon = createIcon("Add01Icon");
export const AiChipIcon = createIcon("AiChipIcon");
export const AlarmClockIcon = createIcon("AlarmClockIcon");
export const Alert01Icon = createIcon("Alert01Icon");
export const AlertCircleIcon = createIcon("AlertCircleIcon");
export const Analytics01Icon = createIcon("Analytics01Icon");
export const ArrowDown01Icon = createIcon("ArrowDown01Icon");
export const ArrowDown02Icon = createIcon("ArrowDown02Icon");
export const ArrowDownIcon = createIcon("ArrowDownIcon");
export const ArrowLeft01Icon = createIcon("ArrowLeft01Icon");
export const ArrowRight01Icon = createIcon("ArrowRight01Icon");
export const ArrowUp01Icon = createIcon("ArrowUp01Icon");
export const ArrowUp02Icon = createIcon("ArrowUp02Icon");
export const ArrowUpRight01Icon = createIcon("ArrowUpRight01Icon");
export const BarChartIcon = createIcon("BarChartIcon");
export const BodyPartMuscleIcon = createIcon("BodyPartMuscleIcon");
export const BookOpen01Icon = createIcon("BookOpen01Icon");
export const Brain02Icon = createIcon("Brain02Icon");
export const BrainIcon = createIcon("BrainIcon");
export const BubbleChatAddIcon = createIcon("BubbleChatAddIcon");
export const BubbleChatIcon = createIcon("BubbleChatIcon");
export const Calendar03Icon = createIcon("Calendar03Icon");
export const Call02Icon = createIcon("Call02Icon");
export const Camera01Icon = createIcon("Camera01Icon");
export const Cancel01Icon = createIcon("Cancel01Icon");
export const ChartLineData01Icon = createIcon("ChartLineData01Icon");
export const ChartLineData02Icon = createIcon("ChartLineData02Icon");
export const ChartRingIcon = createIcon("ChartRingIcon");
export const CheckListIcon = createIcon("CheckListIcon");
export const CheckmarkCircle01Icon = createIcon("CheckmarkCircle01Icon");
export const CheckmarkCircle02Icon = createIcon("CheckmarkCircle02Icon");
export const CheckmarkSquare03Icon = createIcon("CheckmarkSquare03Icon");
export const Clock01Icon = createIcon("Clock01Icon");
export const Clock04Icon = createIcon("Clock04Icon");
export const CloudAngledRainIcon = createIcon("CloudAngledRainIcon");
export const CloudAngledZapIcon = createIcon("CloudAngledZapIcon");
export const CloudFastWindIcon = createIcon("CloudFastWindIcon");
export const CloudIcon = createIcon("CloudIcon");
export const CloudLittleRainIcon = createIcon("CloudLittleRainIcon");
export const CloudSnowIcon = createIcon("CloudSnowIcon");
export const CodeIcon = createIcon("CodeIcon");
export const Comment01Icon = createIcon("Comment01Icon");
export const ComputerTerminal01Icon = createIcon("ComputerTerminal01Icon");
export const ConnectIcon = createIcon("ConnectIcon");
export const Contact01Icon = createIcon("Contact01Icon");
export const Copy01Icon = createIcon("Copy01Icon");
export const CpuIcon = createIcon("CpuIcon");
export const CreditCardIcon = createIcon("CreditCardIcon");
export const CustomerSupportIcon = createIcon("CustomerSupportIcon");
export const Delete01Icon = createIcon("Delete01Icon");
export const Delete02Icon = createIcon("Delete02Icon");
export const DiscordIcon = createIcon("DiscordIcon");
export const DocumentAttachmentIcon = createIcon("DocumentAttachmentIcon");
export const Download02Icon = createIcon("Download02Icon");
export const Download04Icon = createIcon("Download04Icon");
export const DropletIcon = createIcon("DropletIcon");
export const Edit02Icon = createIcon("Edit02Icon");
export const FastWindIcon = createIcon("FastWindIcon");
export const FavouriteIcon = createIcon("FavouriteIcon");
export const File01Icon = createIcon("File01Icon");
export const FileEmpty02Icon = createIcon("FileEmpty02Icon");
export const Flag02Icon = createIcon("Flag02Icon");
export const FlashIcon = createIcon("FlashIcon");
export const FlowCircleIcon = createIcon("FlowCircleIcon");
export const FlowIcon = createIcon("FlowIcon");
export const Flowchart01Icon = createIcon("Flowchart01Icon");
export const Folder02Icon = createIcon("Folder02Icon");
export const FolderFileStorageIcon = createIcon("FolderFileStorageIcon");
export const FolderIcon = createIcon("FolderIcon");
export const Globe02Icon = createIcon("Globe02Icon");
export const GlobeIcon = createIcon("GlobeIcon");
export const HelpCircleIcon = createIcon("HelpCircleIcon");
export const Image01Icon = createIcon("Image01Icon");
export const Image02Icon = createIcon("Image02Icon");
export const InformationCircleIcon = createIcon("InformationCircleIcon");
export const KeyboardIcon = createIcon("KeyboardIcon");
export const LayoutGridIcon = createIcon("LayoutGridIcon");
export const LinkBackwardIcon = createIcon("LinkBackwardIcon");
export const LinkSquare01Icon = createIcon("LinkSquare01Icon");
export const LinkSquare02Icon = createIcon("LinkSquare02Icon");
export const Loading03Icon = createIcon("Loading03Icon");
export const Location01Icon = createIcon("Location01Icon");
export const Logout01Icon = createIcon("Logout01Icon");
export const MagicWand01Icon = createIcon("MagicWand01Icon");
export const Mail01Icon = createIcon("Mail01Icon");
export const MailOpen01Icon = createIcon("MailOpen01Icon");
export const MailSend01Icon = createIcon("MailSend01Icon");
export const Menu01Icon = createIcon("Menu01Icon");
export const MoreVerticalIcon = createIcon("MoreVerticalIcon");
export const Message01Icon = createIcon("Message01Icon");
export const MessageMultiple01Icon = createIcon("MessageMultiple01Icon");
export const News01Icon = createIcon("News01Icon");
export const Notification01Icon = createIcon("Notification01Icon");
export const Notification02Icon = createIcon("Notification02Icon");
export const NotificationIcon = createIcon("NotificationIcon");
export const PackageOpenIcon = createIcon("PackageOpenIcon");
export const PencilEdit01Icon = createIcon("PencilEdit01Icon");
export const PencilEdit02Icon = createIcon("PencilEdit02Icon");
export const PieChart01Icon = createIcon("PieChart01Icon");
export const Pin02Icon = createIcon("Pin02Icon");
export const PlayIcon = createIcon("PlayIcon");
export const PlusSignIcon = createIcon("PlusSignIcon");
export const PuzzleIcon = createIcon("PuzzleIcon");
export const RepeatIcon = createIcon("RepeatIcon");
export const Search01Icon = createIcon("Search01Icon");
export const SentIcon = createIcon("SentIcon");
export const Settings01Icon = createIcon("Settings01Icon");
export const Settings02Icon = createIcon("Settings02Icon");
export const Share01Icon = createIcon("Share01Icon");
export const Share08Icon = createIcon("Share08Icon");
export const ShieldUserIcon = createIcon("ShieldUserIcon");
export const SourceCodeCircleIcon = createIcon("SourceCodeCircleIcon");
export const SquareArrowUpRight02Icon = createIcon("SquareArrowUpRight02Icon");
export const Sun03Icon = createIcon("Sun03Icon");
export const SunriseIcon = createIcon("SunriseIcon");
export const SunsetIcon = createIcon("SunsetIcon");
export const Tag01Icon = createIcon("Tag01Icon");
export const Target02Icon = createIcon("Target02Icon");
export const TaskDailyIcon = createIcon("TaskDailyIcon");
export const TelegramIcon = createIcon("TelegramIcon");
export const ThumbsDownIcon = createIcon("ThumbsDownIcon");
export const ThumbsUpIcon = createIcon("ThumbsUpIcon");
export const Tick01Icon = createIcon("Tick01Icon");
export const Tick02Icon = createIcon("Tick02Icon");
export const ToggleOffIcon = createIcon("ToggleOffIcon");
export const ToggleOnIcon = createIcon("ToggleOnIcon");
export const ToolsIcon = createIcon("ToolsIcon");
export const Tornado02Icon = createIcon("Tornado02Icon");
export const TranslationIcon = createIcon("TranslationIcon");
export const TwitterIcon = createIcon("TwitterIcon");
export const UploadCircle01Icon = createIcon("UploadCircle01Icon");
export const UserCircle02Icon = createIcon("UserCircle02Icon");
export const UserCircleIcon = createIcon("UserCircleIcon");
export const UserGroupIcon = createIcon("UserGroupIcon");
export const UserIcon = createIcon("UserIcon");
export const UserSearch01Icon = createIcon("UserSearch01Icon");
export const WhatsappIcon = createIcon("WhatsappIcon");
export const WorkflowCircle06Icon = createIcon("WorkflowCircle06Icon");
export const WorkflowSquare10Icon = createIcon("WorkflowSquare10Icon");
export const Wrench01Icon = createIcon("Wrench01Icon");
export const ZapIcon = createIcon("ZapIcon");
