/**
 * @module @gaia/shared/bots
 *
 * Shared bot library for all GAIA platform integrations (Discord, Slack, Telegram): adapter/
 * (BaseBotAdapter + renderer), commands/ (unified BotCommand definitions), types/, api/
 * (GaiaClient), config/ (env loader), and utils/ (formatters, command handlers, streaming).
 *
 * New command: add it under commands/<name>.ts and to the allCommands array in commands/index.ts.
 * New platform bot: extend BaseBotAdapter under apps/bots/<platform>/ and call adapter.boot(allCommands).
 */
export {
  BaseBotAdapter,
  BotServer,
  richMessageToMarkdown,
  runBotProcess,
} from "./adapter";

export { GaiaApiError, GaiaClient } from "./api";
export {
  allCommands,
  authCommand,
  conversationsCommand,
  gaiaCommand,
  helpCommand,
  newCommand,
  settingsCommand,
  statusCommand,
  stopCommand,
  todoCommand,
  unlinkCommand,
  workflowCommand,
} from "./commands";
export { injectInfisicalSecrets, loadConfig } from "./config";
// Outbound envelope types/schema (zod-only — RN-safe). The full consumer
// (`./consumer/outbound-consumer`) is NOT re-exported here: it imports amqplib
// (Node-only), which Metro/React Native cannot resolve.
export type {
  OutboundAttachment,
  OutboundMessageEnvelope,
  OutboundReaction,
} from "./consumer/envelope";
export {
  outboundAttachmentSchemaFor,
  outboundMessageEnvelopeSchemaFor,
  outboundReactionSchema,
} from "./consumer/envelope";
export {
  buildLinkCodeFailureMessage,
  consumeInboundLinkCode,
  LINK_CODE_LENGTH,
  parseTrailingLinkCode,
  redeemLinkCode,
} from "./link-codes";
export type {
  InboundLinkCodeArgs,
  LinkCodeFailure,
  LinkState,
  ParsedLinkCode,
} from "./link-codes.types";
export type {
  AuthenticatedSettingsResponse,
  AuthStatus,
  BotCommand,
  BotCommandOption,
  BotConfig,
  BotConversation,
  BotConversationListResponse,
  BotCreateTodoRequest,
  BotFileData,
  BotIntegrationInfo,
  BotSubcommand,
  BotTodo,
  BotTodoListResponse,
  BotUserContext,
  BotWorkflow,
  BotWorkflowExecutionRequest,
  BotWorkflowExecutionResponse,
  BotWorkflowListResponse,
  ChatRequest,
  CommandContext,
  CommandExecuteParams,
  MessageTarget,
  PlatformName,
  RichMessage,
  RichMessageTarget,
  SentMessage,
  SettingsResponse,
  UnauthenticatedSettingsResponse,
} from "./types";
export type {
  BotFailureReason,
  BotLogFields,
  BotLogger,
  BotLogLevel,
  BotWideEventFields,
  IncomingMedia,
  MediaKind,
  MediaOutcome,
  MessageEditor,
  NewMessageSender,
  StreamingOptions,
  WideEventBoundaryFields,
  WideEventEntry,
} from "./utils";
export {
  BODY_READ_TIMEOUT,
  BODY_TOO_LARGE,
  BOT_FAILURE_REASON,
  BOT_MEDIA_LIMITS,
  buildAuthLinkMessage,
  buildPlanRequiredMessage,
  COMMAND_HELP,
  chunkResponse,
  classifyBotFailure,
  convertToDiscordMarkdown,
  convertToImessageText,
  convertToSlackMrkdwn,
  convertToTelegramHtml,
  convertToWhatsAppMarkdown,
  createBotLogger,
  dispatchTodoSubcommand,
  dispatchWorkflowSubcommand,
  emitBotLogLine,
  escapeHtml,
  escapeHtmlAttr,
  extensionForMime,
  extractSubcommandArgs,
  fetchBytesCapped,
  formatBotError,
  formatConversation,
  formatConversationList,
  formatTodo,
  formatTodoList,
  formatWorkflow,
  formatWorkflowList,
  friendlyMediaError,
  getHttpStatus,
  handleConversationList,
  handleNewConversation,
  handleStreamingChat,
  handleTodoComplete,
  handleTodoCreate,
  handleTodoDelete,
  handleTodoList,
  handleWorkflowCreate,
  handleWorkflowDelete,
  handleWorkflowExecute,
  handleWorkflowGet,
  handleWorkflowList,
  hashLogIdentifier,
  htmlToPlainText,
  isTableRow,
  isTableSeparator,
  MEDIA_READ_TIMEOUT_MS,
  MediaReadTimeoutError,
  mediaKindFromMime,
  OUTBOUND_FILE_LIMITS,
  PLATFORM_LIMITS,
  PLATFORM_MARKDOWN,
  parseTextArgs,
  processBotMedia,
  readBodyBounded,
  readBodyBytesBounded,
  readResponseBytesCapped,
  readStreamBytesCapped,
  recordBotFailure,
  renderForPlatform,
  STREAMING_DEFAULTS,
  sanitizeErrorForLog,
  segmentIntoBubbles,
  sendChunked,
  unfetchableMediaMessage,
  unsupportedMediaMessage,
  WEBHOOK_BODY_READ_TIMEOUT_MS,
  WEBHOOK_MAX_BODY_BYTES,
  WIDE_EVENT_MESSAGE,
  wideLog,
  withWideEvent,
} from "./utils";
