"""GitHub plan-and-execute subgraph built from reusable configuration."""

# Pull Request Management Tools
PULL_REQUEST_TOOLS = [
    "GITHUB_CREATE_A_PULL_REQUEST",
    "GITHUB_GET_A_PULL_REQUEST",
    "GITHUB_LIST_PULL_REQUESTS",
    "GITHUB_UPDATE_A_PULL_REQUEST",
    "GITHUB_MERGE_A_PULL_REQUEST",
    "GITHUB_LIST_COMMITS_ON_A_PULL_REQUEST",
    "GITHUB_LIST_PULL_REQUESTS_FILES",
]

# PR Review Management Tools
PR_REVIEW_TOOLS = [
    "GITHUB_REQUEST_REVIEWERS_FOR_A_PULL_REQUEST",
    "GITHUB_REMOVE_REQUESTED_REVIEWERS_FROM_A_PULL_REQUEST",
    "GITHUB_CREATE_A_REVIEW_FOR_A_PULL_REQUEST",
    "GITHUB_SUBMIT_A_REVIEW_FOR_A_PULL_REQUEST",
    "GITHUB_GET_A_REVIEW_FOR_A_PULL_REQUEST",
    "GITHUB_LIST_REVIEWS_FOR_A_PULL_REQUEST",
    "GITHUB_DISMISS_A_REVIEW_FOR_A_PULL_REQUEST",
]

# Issue Management Tools
ISSUE_TOOLS = [
    "GITHUB_CREATE_AN_ISSUE",
    "GITHUB_GET_AN_ISSUE",
    "GITHUB_UPDATE_AN_ISSUE",
    "GITHUB_LIST_REPOSITORY_ISSUES",
    "GITHUB_LOCK_AN_ISSUE",
    "GITHUB_UNLOCK_AN_ISSUE",
    "GITHUB_SEARCH_ISSUES_AND_PULL_REQUESTS",
    "GITHUB_LIST_ISSUES_ASSIGNED_TO_THE_AUTHENTICATED_USER",
]

# Assignee Management Tools
ASSIGNEE_TOOLS = [
    "GITHUB_ADD_ASSIGNEES_TO_AN_ISSUE",
    "GITHUB_REMOVE_ASSIGNEES_FROM_AN_ISSUE",
    "GITHUB_LIST_ASSIGNEES",
    "GITHUB_CHECK_IF_A_USER_CAN_BE_ASSIGNED",
]

# Label Management Tools
LABEL_TOOLS = [
    "GITHUB_CREATE_A_LABEL",
    "GITHUB_GET_A_LABEL",
    "GITHUB_UPDATE_A_LABEL",
    "GITHUB_DELETE_A_LABEL",
    "GITHUB_LIST_LABELS_FOR_A_REPOSITORY",
    "GITHUB_ADD_LABELS_TO_AN_ISSUE",
    "GITHUB_REMOVE_A_LABEL_FROM_AN_ISSUE",
    "GITHUB_LIST_LABELS_FOR_AN_ISSUE",
    "GITHUB_SET_LABELS_FOR_AN_ISSUE",
]

# Comment Management Tools
COMMENT_TOOLS = [
    "GITHUB_CREATE_AN_ISSUE_COMMENT",
    "GITHUB_GET_AN_ISSUE_COMMENT",
    "GITHUB_UPDATE_AN_ISSUE_COMMENT",
    "GITHUB_DELETE_AN_ISSUE_COMMENT",
    "GITHUB_LIST_ISSUE_COMMENTS",
    "GITHUB_CREATE_A_COMMIT_COMMENT",
    "GITHUB_LIST_COMMIT_COMMENTS_FOR_A_REPOSITORY",
    "GITHUB_CREATE_A_REVIEW_COMMENT_FOR_A_PULL_REQUEST",
    "GITHUB_GET_A_REVIEW_COMMENT_FOR_A_PULL_REQUEST",
    "GITHUB_LIST_REVIEW_COMMENTS_ON_A_PULL_REQUEST",
]

# Commit Operations Tools
COMMIT_TOOLS = [
    "GITHUB_GET_A_COMMIT",
    "GITHUB_LIST_COMMITS",
    "GITHUB_COMPARE_TWO_COMMITS",
    "GITHUB_LIST_BRANCHES_FOR_HEAD_COMMIT",
]

# Repository Management Tools
REPOSITORY_MANAGEMENT_TOOLS = [
    "GITHUB_GET_A_REPOSITORY",
    "GITHUB_CREATE_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER",
    "GITHUB_LIST_REPOSITORIES_FOR_THE_AUTHENTICATED_USER",
    "GITHUB_LIST_ORGANIZATION_REPOSITORIES",
    "GITHUB_LIST_ORGANIZATIONS",
    "GITHUB_CREATE_A_FORK",
    "GITHUB_SEARCH_REPOSITORIES",
    "GITHUB_ADD_A_REPOSITORY_COLLABORATOR",
    "GITHUB_STAR_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER",
    "GITHUB_UNSTAR_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER",
]

# Repository Content Tools
REPOSITORY_CONTENT_TOOLS = [
    "GITHUB_GET_REPOSITORY_CONTENT",
    "GITHUB_CREATE_OR_UPDATE_FILE_CONTENTS",
    "GITHUB_DELETE_A_FILE",
    "GITHUB_GET_A_REPOSITORY_README",
]

# Branch Management Tools
BRANCH_TOOLS = [
    "GITHUB_GET_A_BRANCH",
    "GITHUB_LIST_BRANCHES",
    "GITHUB_MERGE_A_BRANCH",
    "GITHUB_GET_BRANCH_PROTECTION",
    "GITHUB_UPDATE_BRANCH_PROTECTION",
    "GITHUB_DELETE_BRANCH_PROTECTION",
]

AUTHENTICATED_USER_TOOLS = [
    "GITHUB_GET_THE_AUTHENTICATED_USER",
    "GITHUB_LIST_EMAIL_ADDRESSES_FOR_THE_AUTHENTICATED_USER",
    "GITHUB_LIST_ORGANIZATIONS_FOR_THE_AUTHENTICATED_USER",
    "GITHUB_LIST_PUBLIC_EMAIL_ADDRESSES_FOR_THE_AUTHENTICATED_USER",
    "GITHUB_LIST_SOCIAL_ACCOUNTS_FOR_THE_AUTHENTICATED_USER",
]

# All tools used in GitHub subgraph (merged from all categories)
GITHUB_TOOLS = (
    PULL_REQUEST_TOOLS
    + PR_REVIEW_TOOLS
    + ISSUE_TOOLS
    + ASSIGNEE_TOOLS
    + LABEL_TOOLS
    + COMMENT_TOOLS
    + COMMIT_TOOLS
    + REPOSITORY_MANAGEMENT_TOOLS
    + REPOSITORY_CONTENT_TOOLS
    + BRANCH_TOOLS
    + AUTHENTICATED_USER_TOOLS
)
