"""Gmail plan-and-execute subgraph built from reusable configuration."""

# Email Composition Tools
EMAIL_COMPOSITION_TOOLS = [
    "GMAIL_CREATE_EMAIL_DRAFT",
    "GMAIL_SEND_EMAIL",
    "GMAIL_SEND_DRAFT",
    "GMAIL_LIST_DRAFTS",
    "GMAIL_DELETE_DRAFT",
    "GMAIL_REPLY_TO_THREAD",
    "GMAIL_FORWARD_MESSAGE",
]

# Email Retrieval Tools
EMAIL_RETRIEVAL_TOOLS = [
    "GMAIL_FETCH_EMAILS",
    "GMAIL_FETCH_MESSAGE_BY_MESSAGE_ID",
    "GMAIL_FETCH_MESSAGE_BY_THREAD_ID",
    "GMAIL_LIST_THREADS",
]

# Email Management Tools
EMAIL_MANAGEMENT_TOOLS = [
    "GMAIL_ADD_LABEL_TO_EMAIL",
    "GMAIL_CREATE_LABEL",
    "GMAIL_LIST_LABELS",
    "GMAIL_MODIFY_THREAD_LABELS",
    "GMAIL_PATCH_LABEL",
    "GMAIL_REMOVE_LABEL",
    "GMAIL_DELETE_MESSAGE",
    "GMAIL_MOVE_TO_TRASH",
]

# Contact Management Tools
CONTACT_MANAGEMENT_TOOLS = [
    "GMAIL_GET_CONTACTS",
    "GMAIL_GET_PEOPLE",
    "GMAIL_GET_PROFILE",
    "GMAIL_SEARCH_PEOPLE",
]

# Attachment Handling Tools
ATTACHMENT_HANDLING_TOOLS = [
    "GMAIL_GET_ATTACHMENT",
]

# All tools used in Gmail subgraph (merged from all categories)
GMAIL_TOOLS = (
    EMAIL_COMPOSITION_TOOLS
    + EMAIL_RETRIEVAL_TOOLS
    + EMAIL_MANAGEMENT_TOOLS
    + CONTACT_MANAGEMENT_TOOLS
    + ATTACHMENT_HANDLING_TOOLS
)
