import {
  AbacusIcon,
  AiBrain01Icon,
  AiMagicIcon,
  Airplane01Icon,
  AlarmClockIcon,
  AnalyticsUpIcon,
  ApiIcon,
  AppleIcon,
  ArchiveIcon,
  ArtboardIcon,
  Award01Icon,
  BackpackIcon,
  BankIcon,
  BeachIcon,
  BedIcon,
  BirthdayCakeIcon,
  Bitcoin01Icon,
  Book01Icon,
  Book02Icon,
  BookmarkIcon,
  Briefcase01Icon,
  Bug01Icon,
  Building01Icon,
  Bus01Icon,
  Calculator01Icon,
  Calendar01Icon,
  Calendar03Icon,
  CalendarAdd01Icon,
  Call02Icon,
  CallIncoming02Icon,
  Camera01Icon,
  Car01Icon,
  Certificate01Icon,
  ChampionIcon,
  Chart01Icon,
  ChartBarLineIcon,
  ChartUpIcon,
  Chat01Icon,
  ChatBotIcon,
  CheckListIcon,
  CheckmarkCircle01Icon,
  ChefHatIcon,
  ChessIcon,
  ClipboardIcon,
  Clock01Icon,
  CloudIcon,
  Coffee01Icon,
  Coins01Icon,
  CommandIcon,
  CommentAdd01Icon,
  Compass01Icon,
  ComputerTerminal01Icon,
  Contact01Icon,
  CreditCardIcon,
  CrownIcon,
  Database01Icon,
  DiamondIcon,
  DiceIcon,
  DiscordIcon,
  DollarCircleIcon,
  Dumbbell01Icon,
  Dumbbell02Icon,
  Film01Icon,
  FingerPrintIcon,
  FireIcon,
  Flag01Icon,
  FlashIcon,
  FlowerIcon,
  FolderIcon,
  GameController01Icon,
  GiftIcon,
  GitBranchIcon,
  GitCommitIcon,
  GlobeIcon,
  GraduationScrollIcon,
  HeadphonesIcon,
  HeartAddIcon,
  HeartCheckIcon,
  Home01Icon,
  HourglassIcon,
  IceCreamIcon,
  type IconProps,
  Idea01Icon,
  Image01Icon,
  InboxIcon,
  Invoice01Icon,
  JoystickIcon,
  Key01Icon,
  Layers01Icon,
  Leaf01Icon,
  LinkSquare01Icon,
  ListViewIcon,
  Location01Icon,
  LockIcon,
  Luggage01Icon,
  MagicWand01Icon,
  Mail01Icon,
  MailSend01Icon,
  MapsIcon,
  Medicine01Icon,
  MedicineBottle01Icon,
  Megaphone01Icon,
  Message01Icon,
  Mic01Icon,
  Money01Icon,
  MoneyBag01Icon,
  Moon01Icon,
  MountainIcon,
  MusicNote01Icon,
  Note01Icon,
  Notebook01Icon,
  NotificationIcon,
  Package01Icon,
  PartyIcon,
  Passport01Icon,
  Pen01Icon,
  PencilEdit01Icon,
  PiggyBankIcon,
  PinLocation01Icon,
  Pizza01Icon,
  PlugSocketIcon,
  PodcastIcon,
  PresentationIcon,
  PuzzleIcon,
  RainIcon,
  ReceiptDollarIcon,
  Restaurant01Icon,
  Robot01Icon,
  Rocket01Icon,
  RulerIcon,
  RunningShoesIcon,
  SafeIcon,
  SchoolIcon,
  SecurityIcon,
  SendingOrderIcon,
  Settings01Icon,
  Share01Icon,
  Shield01Icon,
  ShoppingBag01Icon,
  ShoppingCart01Icon,
  SlackIcon,
  SleepingIcon,
  SmartPhone01Icon,
  SmileIcon,
  SofaIcon,
  SourceCodeIcon,
  SparklesIcon,
  StarIcon,
  StickyNote01Icon,
  StopWatchIcon,
  StudyLampIcon,
  Sun01Icon,
  Target01Icon,
  Task01Icon,
  TaskDone01Icon,
  TelegramIcon,
  Telescope01Icon,
  TestTube01Icon,
  ThumbsUpIcon,
  Ticket01Icon,
  Time04Icon,
  Timer01Icon,
  TimeScheduleIcon,
  Train01Icon,
  TreeIcon,
  Tv01Icon,
  UserAdd01Icon,
  UserGroupIcon,
  UserIcon,
  VacuumCleanerIcon,
  Video01Icon,
  Video02Icon,
  Wallet01Icon,
  Watch01Icon,
  WhatsappIcon,
  WifiIcon,
  Wrench01Icon,
  Yoga01Icon,
  ZapIcon,
} from "@icons";
import type { ComponentType } from "react";

export interface WorkflowIconDef {
  /** Stored slug — the gaia-icons component export name */
  name: string;
  Icon: ComponentType<IconProps>;
  keywords: string[];
}

/** Compact catalog row: [slug, component, space-separated keywords]. */
function def(
  name: string,
  Icon: ComponentType<IconProps>,
  keywords: string,
): WorkflowIconDef {
  return { name, Icon, keywords: keywords.split(" ") };
}

/** The curated set of icons a workflow can use, with search keywords. */
export const WORKFLOW_ICON_CATALOG: WorkflowIconDef[] = [
  def("Mail01Icon", Mail01Icon, "email inbox gmail newsletter"),
  def("InboxIcon", InboxIcon, "email mail unread"),
  def("MailSend01Icon", MailSend01Icon, "email outbox send compose"),
  def("Message01Icon", Message01Icon, "sms text chat dm"),
  def("Chat01Icon", Chat01Icon, "conversation message bubble dm"),
  def("ChatBotIcon", ChatBotIcon, "assistant ai support conversation"),
  def("Call02Icon", Call02Icon, "phone voice dial telephone"),
  def("CallIncoming02Icon", CallIncoming02Icon, "phone ringing answer voice"),
  def("Video01Icon", Video01Icon, "call zoom meeting conference"),
  def("SmartPhone01Icon", SmartPhone01Icon, "mobile cell device text"),
  def(
    "Megaphone01Icon",
    Megaphone01Icon,
    "announcement broadcast alert promote",
  ),
  def("NotificationIcon", NotificationIcon, "alert bell reminder ping"),
  def("SendingOrderIcon", SendingOrderIcon, "send submit dispatch paper plane"),
  def("CommentAdd01Icon", CommentAdd01Icon, "comment reply feedback note"),
  def("WhatsappIcon", WhatsappIcon, "whatsapp messaging chat"),
  def("TelegramIcon", TelegramIcon, "telegram messaging chat bot"),
  def("SlackIcon", SlackIcon, "slack team chat workspace"),
  def("DiscordIcon", DiscordIcon, "discord community server chat"),
  def("Contact01Icon", Contact01Icon, "contact address book person crm"),
  def("Calendar01Icon", Calendar01Icon, "schedule date event planner"),
  def("Calendar03Icon", Calendar03Icon, "schedule date event agenda"),
  def(
    "CalendarAdd01Icon",
    CalendarAdd01Icon,
    "schedule new event booking plan",
  ),
  def("Clock01Icon", Clock01Icon, "time hour schedule duration"),
  def("AlarmClockIcon", AlarmClockIcon, "wake up reminder alert morning"),
  def("Timer01Icon", Timer01Icon, "countdown stopwatch duration pomodoro"),
  def("StopWatchIcon", StopWatchIcon, "timer duration race speed"),
  def("HourglassIcon", HourglassIcon, "waiting time pending sand timer"),
  def("TimeScheduleIcon", TimeScheduleIcon, "calendar planner agenda booking"),
  def("Watch01Icon", Watch01Icon, "time wristwatch wearable clock"),
  def("Time04Icon", Time04Icon, "clock duration deadline schedule"),
  def("Task01Icon", Task01Icon, "todo checklist action item"),
  def("TaskDone01Icon", TaskDone01Icon, "complete checked finished todo"),
  def("CheckListIcon", CheckListIcon, "todo list tasks agenda"),
  def(
    "CheckmarkCircle01Icon",
    CheckmarkCircle01Icon,
    "done approved success verified",
  ),
  def("Note01Icon", Note01Icon, "memo notes writing journal"),
  def("StickyNote01Icon", StickyNote01Icon, "reminder memo post-it notes"),
  def("Notebook01Icon", Notebook01Icon, "journal diary notes log"),
  def("Pen01Icon", Pen01Icon, "write edit draft sign"),
  def("PencilEdit01Icon", PencilEdit01Icon, "edit draft write revise"),
  def("Flag01Icon", Flag01Icon, "milestone goal priority mark"),
  def("PinLocation01Icon", PinLocation01Icon, "pin save bookmark location"),
  def("ListViewIcon", ListViewIcon, "list items outline agenda"),
  def("FolderIcon", FolderIcon, "files directory organize storage"),
  def("ArchiveIcon", ArchiveIcon, "storage backup old records"),
  def("ClipboardIcon", ClipboardIcon, "copy paste checklist report"),
  def("Layers01Icon", Layers01Icon, "stack organize grouping workflow"),
  def("Briefcase01Icon", Briefcase01Icon, "work job office business"),
  def("PresentationIcon", PresentationIcon, "slides meeting pitch deck"),
  def("ChartUpIcon", ChartUpIcon, "growth analytics revenue trend"),
  def("AnalyticsUpIcon", AnalyticsUpIcon, "metrics growth reporting stats"),
  def("Target01Icon", Target01Icon, "goal objective focus kpi"),
  def(
    "Building01Icon",
    Building01Icon,
    "office company headquarters corporate",
  ),
  def("ChartBarLineIcon", ChartBarLineIcon, "analytics report dashboard data"),
  def("Idea01Icon", Idea01Icon, "lightbulb brainstorm innovation insight"),
  def("Chart01Icon", Chart01Icon, "graph data report dashboard"),
  def("SourceCodeIcon", SourceCodeIcon, "code programming developer script"),
  def(
    "ComputerTerminal01Icon",
    ComputerTerminal01Icon,
    "terminal shell console cli",
  ),
  def("GitBranchIcon", GitBranchIcon, "git version control repo merge"),
  def("GitCommitIcon", GitCommitIcon, "git commit version control repo"),
  def("Database01Icon", Database01Icon, "data storage sql server"),
  def("CloudIcon", CloudIcon, "cloud storage server hosting"),
  def("Bug01Icon", Bug01Icon, "bug error debug issue"),
  def("ApiIcon", ApiIcon, "api integration endpoint webhook"),
  def("CommandIcon", CommandIcon, "shortcut keyboard cli hotkey"),
  def("LinkSquare01Icon", LinkSquare01Icon, "url link connect integration"),
  def("AiMagicIcon", AiMagicIcon, "ai generate smart assistant"),
  def("AiBrain01Icon", AiBrain01Icon, "ai intelligence model neural"),
  def("Robot01Icon", Robot01Icon, "bot automation ai agent"),
  def("SparklesIcon", SparklesIcon, "ai magic generate new"),
  def("MagicWand01Icon", MagicWand01Icon, "ai auto magic generate"),
  def("ZapIcon", ZapIcon, "fast instant automation trigger"),
  def("FlashIcon", FlashIcon, "quick instant power trigger"),
  def("Money01Icon", Money01Icon, "cash finance budget payment"),
  def("MoneyBag01Icon", MoneyBag01Icon, "savings cash budget earnings"),
  def("Wallet01Icon", Wallet01Icon, "payment budget cash finance"),
  def("CreditCardIcon", CreditCardIcon, "payment billing card subscription"),
  def("BankIcon", BankIcon, "finance account savings institution"),
  def("Invoice01Icon", Invoice01Icon, "billing receipt payment invoice"),
  def("DollarCircleIcon", DollarCircleIcon, "money price currency finance"),
  def("Coins01Icon", Coins01Icon, "money savings currency cash"),
  def(
    "ReceiptDollarIcon",
    ReceiptDollarIcon,
    "expense billing purchase receipt",
  ),
  def("PiggyBankIcon", PiggyBankIcon, "savings budget finance money"),
  def("Bitcoin01Icon", Bitcoin01Icon, "crypto currency blockchain money"),
  def("Dumbbell01Icon", Dumbbell01Icon, "gym workout fitness training"),
  def("Dumbbell02Icon", Dumbbell02Icon, "gym exercise fitness strength"),
  def("HeartCheckIcon", HeartCheckIcon, "health wellness checkup cardio"),
  def("HeartAddIcon", HeartAddIcon, "love favorite health wellness"),
  def("Medicine01Icon", Medicine01Icon, "pills medication health pharmacy"),
  def(
    "MedicineBottle01Icon",
    MedicineBottle01Icon,
    "pills prescription pharmacy health",
  ),
  def("RunningShoesIcon", RunningShoesIcon, "run jog cardio exercise"),
  def("Yoga01Icon", Yoga01Icon, "meditation wellness stretch mindfulness"),
  def("SleepingIcon", SleepingIcon, "sleep rest bedtime nap"),
  def("Book01Icon", Book01Icon, "read study learn library"),
  def("Book02Icon", Book02Icon, "read study novel textbook"),
  def(
    "GraduationScrollIcon",
    GraduationScrollIcon,
    "diploma graduate degree school",
  ),
  def("SchoolIcon", SchoolIcon, "education class university college"),
  def("Telescope01Icon", Telescope01Icon, "science research astronomy explore"),
  def("TestTube01Icon", TestTube01Icon, "science lab chemistry experiment"),
  def("BookmarkIcon", BookmarkIcon, "save favorite reading mark"),
  def("RulerIcon", RulerIcon, "measure geometry school design"),
  def("Calculator01Icon", Calculator01Icon, "math numbers finance compute"),
  def("AbacusIcon", AbacusIcon, "math counting education arithmetic"),
  def(
    "Certificate01Icon",
    Certificate01Icon,
    "diploma award credential achievement",
  ),
  def("StudyLampIcon", StudyLampIcon, "study desk read focus"),
  def("Home01Icon", Home01Icon, "house residence chores household"),
  def(
    "ShoppingCart01Icon",
    ShoppingCart01Icon,
    "shopping groceries checkout buy",
  ),
  def("ShoppingBag01Icon", ShoppingBag01Icon, "shopping retail purchase store"),
  def("GiftIcon", GiftIcon, "present birthday surprise reward"),
  def("Package01Icon", Package01Icon, "delivery shipping parcel order"),
  def("Wrench01Icon", Wrench01Icon, "repair fix maintenance tools"),
  def("SofaIcon", SofaIcon, "furniture living room home couch"),
  def("BedIcon", BedIcon, "sleep bedroom rest furniture"),
  def("PlugSocketIcon", PlugSocketIcon, "electricity power outlet utility"),
  def("VacuumCleanerIcon", VacuumCleanerIcon, "clean chores housework tidy"),
  def("Airplane01Icon", Airplane01Icon, "flight travel trip vacation"),
  def("Car01Icon", Car01Icon, "drive commute vehicle road trip"),
  def("MapsIcon", MapsIcon, "navigation directions location route"),
  def("Compass01Icon", Compass01Icon, "navigation direction explore travel"),
  def("Luggage01Icon", Luggage01Icon, "travel suitcase packing trip"),
  def("Passport01Icon", Passport01Icon, "travel id visa abroad"),
  def("Ticket01Icon", Ticket01Icon, "booking event pass reservation"),
  def("Train01Icon", Train01Icon, "commute railway transit travel"),
  def("Bus01Icon", Bus01Icon, "transit commute public transport travel"),
  def("BackpackIcon", BackpackIcon, "travel hiking school packing"),
  def("BeachIcon", BeachIcon, "vacation summer travel relax"),
  def("MusicNote01Icon", MusicNote01Icon, "song audio playlist spotify"),
  def("Camera01Icon", Camera01Icon, "photo picture capture photography"),
  def("Video02Icon", Video02Icon, "recording clip movie film"),
  def("Image01Icon", Image01Icon, "photo picture gallery media"),
  def("Mic01Icon", Mic01Icon, "microphone voice record podcast"),
  def("HeadphonesIcon", HeadphonesIcon, "audio music listen podcast"),
  def("Film01Icon", Film01Icon, "movie video cinema clip"),
  def("PodcastIcon", PodcastIcon, "audio show episode broadcast"),
  def("Tv01Icon", Tv01Icon, "television screen watch streaming"),
  def("Coffee01Icon", Coffee01Icon, "drink cafe espresso morning"),
  def("Restaurant01Icon", Restaurant01Icon, "dining food reservation eat"),
  def("Pizza01Icon", Pizza01Icon, "food dinner takeout delivery"),
  def("ChefHatIcon", ChefHatIcon, "cooking kitchen recipe chef"),
  def("IceCreamIcon", IceCreamIcon, "dessert treat snack sweet"),
  def("AppleIcon", AppleIcon, "fruit healthy snack nutrition"),
  def(
    "BirthdayCakeIcon",
    BirthdayCakeIcon,
    "celebration birthday dessert party",
  ),
  def("Sun01Icon", Sun01Icon, "weather sunny daytime clear"),
  def("Moon01Icon", Moon01Icon, "night sleep dark mode evening"),
  def("RainIcon", RainIcon, "weather storm forecast wet"),
  def("Leaf01Icon", Leaf01Icon, "nature plant eco green"),
  def("FireIcon", FireIcon, "streak hot trending flame"),
  def("StarIcon", StarIcon, "favorite rating important featured"),
  def("FlowerIcon", FlowerIcon, "nature garden spring bloom"),
  def("MountainIcon", MountainIcon, "hiking outdoors nature adventure"),
  def("TreeIcon", TreeIcon, "nature forest plant outdoors"),
  def("UserIcon", UserIcon, "person profile account contact"),
  def("UserGroupIcon", UserGroupIcon, "team people community group"),
  def("UserAdd01Icon", UserAdd01Icon, "invite follow add contact new member"),
  def("Share01Icon", Share01Icon, "share social post distribute"),
  def("ThumbsUpIcon", ThumbsUpIcon, "like approve vote feedback"),
  def("SmileIcon", SmileIcon, "happy emoji mood feedback"),
  def("Award01Icon", Award01Icon, "achievement recognition prize medal"),
  def("ChampionIcon", ChampionIcon, "trophy winner achievement cup"),
  def("LockIcon", LockIcon, "security private password secure"),
  def("Key01Icon", Key01Icon, "password access credential unlock"),
  def("Shield01Icon", Shield01Icon, "protection security safe defense"),
  def("SafeIcon", SafeIcon, "security vault protect storage"),
  def("SecurityIcon", SecurityIcon, "protection safety shield guard"),
  def(
    "FingerPrintIcon",
    FingerPrintIcon,
    "biometric identity authentication unlock",
  ),
  def("Rocket01Icon", Rocket01Icon, "launch startup boost growth"),
  def("CrownIcon", CrownIcon, "premium vip royalty king"),
  def("DiamondIcon", DiamondIcon, "premium gem luxury valuable"),
  def(
    "GameController01Icon",
    GameController01Icon,
    "gaming play entertainment controller",
  ),
  def("ArtboardIcon", ArtboardIcon, "design color creative art"),
  def("PuzzleIcon", PuzzleIcon, "puzzle solve integration piece"),
  def("GlobeIcon", GlobeIcon, "world global internet international"),
  def("Location01Icon", Location01Icon, "place map pin address gps"),
  def("WifiIcon", WifiIcon, "internet network connectivity wireless"),
  def("Settings01Icon", Settings01Icon, "gear preferences config options"),
  def("PartyIcon", PartyIcon, "celebration event festive fun"),
  def("DiceIcon", DiceIcon, "game random chance gamble"),
  def("ChessIcon", ChessIcon, "strategy game board game chess"),
  def("JoystickIcon", JoystickIcon, "gaming arcade controller play"),
];
