apiVersion: 1

deleteDatasources:
  - name: Loki
    orgId: 1
  - name: Prometheus
    orgId: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    version: 1
    editable: false
    jsonData:
      maxLines: 5000
      timeout: 60

  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s
