from collections.abc import Mapping

from fastapi import APIRouter, Depends, HTTPException

from app.api.v1.dependencies.oauth_dependencies import get_current_user
from app.constants.cache import PLATFORM_LINK_TOKEN_PREFIX
from app.db.redis import redis_cache
from app.decorators import enforce_rate_limit
from app.models.platform_models import (
    DisconnectPlatformResponse,
    GetPlatformLinksResponse,
    InitiatePlatformConnectRequest,
    InitiatePlatformConnectResponse,
    LinkPlatformRequest,
    LinkPlatformResponse,
    MintPlatformLinkCodeResponse,
)
from app.models.user_models import AuthenticatedUser
from app.services.account_fs import schedule_account_sync
from app.services.onboarding.first_message import compose_first_message
from app.services.onboarding.onboarding_service import get_user_onboarding_status
from app.services.platform_link_code_service import (
    build_handoff_links,
    build_handoff_text,
    mint_platform_link_code,
)
from app.services.platform_link_completion import complete_platform_link
from app.services.platform_link_service import (
    Platform,
    PlatformLinkService,
    disconnect_platform_account,
    require_platform_plan,
    start_platform_connect,
)
from app.utils.errors import create_error
from shared.py.wide_events import log

PLATFORM_LINK_CODE_FEATURE_KEY = "platform_link_code"

router = APIRouter()


def _require_user_id(current_user: Mapping[str, object]) -> str:
    user_id = current_user.get("user_id")
    if not isinstance(user_id, str):
        raise create_error(
            message="user_id must be a string",
            why="authenticated session resolved without a string user_id",
            fix="re-authenticate and retry; report if it persists",
            status_code=500,
        )
    return user_id


@router.get("", response_model=GetPlatformLinksResponse)
async def get_platform_links(
    current_user: AuthenticatedUser = Depends(get_current_user),
) -> GetPlatformLinksResponse:
    """Get user's connected platform accounts."""
    if not current_user:
        raise HTTPException(status_code=401, detail="Not authenticated")

    user_id = _require_user_id(current_user)
    log.set(user={"id": user_id}, operation="get_platform_links")
    platform_links = await PlatformLinkService.get_linked_platforms(user_id)
    log.set(outcome="success", result_count=len(platform_links))

    # Constructing the response is the validation boundary — see PlatformLinkEntry
    # on why the service hands these over unvalidated.
    return GetPlatformLinksResponse(platform_links=platform_links)


# Declared before /{platform}: FastAPI matches in definition order, so the
# parameterized route would otherwise swallow this literal path.
@router.post("/code")
async def mint_link_code(
    current_user: AuthenticatedUser = Depends(get_current_user),
) -> MintPlatformLinkCodeResponse:
    """Mint a single-use code that links the user on their first bot message.

    The code carries the opening message composed from their onboarding answers,
    so the platform they pick starts a real conversation instead of asking them
    to type /auth.
    """
    if not current_user:
        raise HTTPException(status_code=401, detail="Not authenticated")

    user_id = _require_user_id(current_user)
    log.set(user={"id": user_id}, operation="mint_platform_link_code")

    await enforce_rate_limit(user_id, PLATFORM_LINK_CODE_FEATURE_KEY)

    status = await get_user_onboarding_status(user_id)
    first_message = compose_first_message(status.preferences)
    code = await mint_platform_link_code(user_id, first_message)

    # The code is the credential — the audit names the actor and the outcome,
    # never the code itself.
    log.audit("platform link code issued", actor=user_id)
    log.set(outcome="success")
    return MintPlatformLinkCodeResponse(
        code=code,
        first_message=first_message,
        handoff_text=build_handoff_text(first_message, code),
        links=build_handoff_links(code, first_message),
    )


@router.post("/{platform}")
async def link_platform(
    platform: str,
    body: LinkPlatformRequest,
    current_user: AuthenticatedUser = Depends(get_current_user),
) -> LinkPlatformResponse:
    """Link a platform account to the authenticated GAIA user.

    Requires a secure token generated by the bot via /api/v1/bot/create-link-token.
    The token is single-use and expires after 10 minutes.
    """
    if not current_user:
        raise HTTPException(status_code=401, detail="Not authenticated")

    if not Platform.is_valid(platform):
        raise HTTPException(status_code=400, detail="Invalid platform")

    # Resolved before the token is redeemed so a rejected redemption — the event
    # worth seeing — still names the session that presented it.
    user_id = _require_user_id(current_user)
    log.set(user={"id": user_id}, operation="link_platform", platform=platform)

    await require_platform_plan(user_id, platform)

    # Look up and consume the token from Redis
    redis_client = redis_cache.client
    token_key = f"{PLATFORM_LINK_TOKEN_PREFIX}:{body.token}"

    token_data = await redis_client.hgetall(token_key)
    if not token_data:
        # Never log body.token — it is the credential. The actor, platform and
        # outcome are what make a replayed or brute-forced link attempt findable.
        log.audit(
            "platform account link rejected",
            actor=user_id,
            provider=platform,
            reason="unknown_or_expired_token",
        )
        raise HTTPException(
            status_code=400,
            detail="Invalid or expired link token. Please request a new link from the bot.",
        )

    # Consume the token immediately to prevent replay attacks
    await redis_client.delete(token_key)

    token_platform = token_data.get("platform", "")
    platform_user_id = token_data.get("platform_user_id", "")

    if not platform_user_id:
        log.audit(
            "platform account link rejected",
            actor=user_id,
            provider=platform,
            reason="malformed_token_data",
        )
        raise HTTPException(status_code=400, detail="Invalid token data")

    # Verify the platform in URL matches the platform in the token
    if token_platform != platform:
        log.audit(
            "platform account link rejected",
            actor=user_id,
            resource=platform_user_id,
            provider=platform,
            reason="platform_mismatch",
        )
        raise HTTPException(
            status_code=400,
            detail="Platform mismatch. This token was not generated for this platform.",
        )

    profile: dict[str, str] = {}
    if token_data.get("username"):
        profile["username"] = token_data["username"]
    if token_data.get("display_name"):
        profile["display_name"] = token_data["display_name"]

    result = await complete_platform_link(
        user_id, platform, platform_user_id, profile=profile or None
    )
    log.set(outcome="success")
    # is_new_link is an internal signal for the greeting, not part of the
    # payload the client reads — build the response field by field.
    return LinkPlatformResponse(
        status=result.status,
        platform=result.platform,
        platform_user_id=result.platform_user_id,
        connected_at=result.connected_at,
    )


# The unlink is audited inside platform_link_service.disconnect_platform_account
# (shared with the agent tool path) so every entry point writes one audit trail.
# evlog-map-disable-next-line audit -- audited in disconnect_platform_account
@router.delete("/{platform}")
async def disconnect_platform(
    platform: str,
    current_user: AuthenticatedUser = Depends(get_current_user),
) -> DisconnectPlatformResponse:
    """Disconnect a platform from user account."""
    if not current_user:
        raise HTTPException(status_code=401, detail="Not authenticated")

    if not Platform.is_valid(platform):
        raise HTTPException(status_code=400, detail="Invalid platform")

    user_id = _require_user_id(current_user)
    log.set(user={"id": user_id}, operation="disconnect_platform", platform=platform)

    result = await disconnect_platform_account(user_id, platform)
    schedule_account_sync(user_id)
    log.set(outcome="success")
    return result


@router.post(
    "/{platform}/connect",
    responses={422: {"description": "iMessage requires an E.164 phone number in the body."}},
)
async def initiate_platform_connect(
    platform: str,
    body: InitiatePlatformConnectRequest,
    current_user: AuthenticatedUser = Depends(get_current_user),
) -> InitiatePlatformConnectResponse:
    """Initiate platform connection via OAuth or manual instructions.

    Returns:
        - OAuth URL if credentials configured
        - Manual instructions if OAuth not configured
    """
    if not current_user:
        raise HTTPException(status_code=401, detail="Not authenticated")

    if not Platform.is_valid(platform):
        raise HTTPException(status_code=400, detail="Invalid platform")

    user_id = _require_user_id(current_user)
    log.set(user={"id": user_id}, operation="initiate_platform_connect", platform=platform)

    result = await start_platform_connect(user_id, platform, phone=body.phone)
    log.set(outcome="success", auth_type=result.auth_type)
    return result
